import type { AuthContext, Env } from '../types.ts';
import { HttpError, enumValue, json, nowMs, optionalInteger, readJson, requireString, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

const types=['protected','self_transfer','planned_transfer','logical','unknown'] as const;
interface Body{fromItemId?:unknown;toItemId?:unknown;connectionType?:unknown;minimumBufferMinutes?:unknown;recommendedBufferMinutes?:unknown;requiresBaggageReclaim?:unknown;requiresImmigration?:unknown;requiresSecurity?:unknown;requiresTerminalChange?:unknown;requiresAirportChange?:unknown;}
export async function listConnections(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT * FROM connections WHERE trip_id=? ORDER BY created_at`).bind(tripId).all();return json({connections:r.results??[]},{},request,env);}
export async function createConnection(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const b=await readJson<Body>(request);const from=requireString(b.fromItemId,'fromItemId',80),to=requireString(b.toItemId,'toItemId',80);if(from===to)throw new HttpError(400,'VALIDATION_ERROR','Connection endpoints must differ.');for(const id of [from,to]){const item=await env.DB.prepare(`SELECT 1 AS ok FROM trip_items WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(id,tripId).first();if(!item)throw new HttpError(400,'ITEM_NOT_IN_TRIP','Connection item does not belong to trip.');}const id=uuid(),now=nowMs();const type=enumValue(b.connectionType,'connectionType',types,'unknown');const min=nonNegative(b.minimumBufferMinutes,'minimumBufferMinutes'),rec=nonNegative(b.recommendedBufferMinutes,'recommendedBufferMinutes');await env.DB.prepare(`INSERT INTO connections(id,trip_id,from_item_id,to_item_id,connection_type,minimum_buffer_minutes,recommended_buffer_minutes,requires_baggage_reclaim,requires_immigration,requires_security,requires_terminal_change,requires_airport_change,user_override,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,1)`).bind(id,tripId,from,to,type,min,rec,bool(b.requiresBaggageReclaim),bool(b.requiresImmigration),bool(b.requiresSecurity),bool(b.requiresTerminalChange),bool(b.requiresAirportChange),now,now).run();const connection=await env.DB.prepare(`SELECT * FROM connections WHERE id=?`).bind(id).first();await recordChangeEvent(env,tripId,'connection',id,'connection_added',null,connection);return json({connection},{status:201},request,env);}
function nonNegative(v:unknown,n:string):number|null{const x=optionalInteger(v,n);if(x!=null&&x<0)throw new HttpError(400,'VALIDATION_ERROR',`${n} must be >= 0.`);return x;}
function bool(v:unknown):number{if(v==null)return 0;if(typeof v!=='boolean')throw new HttpError(400,'VALIDATION_ERROR','Boolean field is invalid.');return v?1:0;}
