import type { AuthContext, Env } from '../types.ts';
import { HttpError, enumValue, json, nowMs, optionalInteger, readJson, requireString, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

const types=['protected','self_transfer','planned_transfer','logical','unknown'] as const;
interface Body{fromItemId?:unknown;toItemId?:unknown;connectionType?:unknown;minimumBufferMinutes?:unknown;recommendedBufferMinutes?:unknown;requiresBaggageReclaim?:unknown;requiresImmigration?:unknown;requiresSecurity?:unknown;requiresTerminalChange?:unknown;requiresAirportChange?:unknown;version?:unknown;}
export async function listConnections(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT c.* FROM connections c JOIN trip_items a ON a.id=c.from_item_id JOIN trip_items b ON b.id=c.to_item_id WHERE c.trip_id=? AND a.deleted_at IS NULL AND b.deleted_at IS NULL ORDER BY c.created_at`).bind(tripId).all();return json({connections:r.results??[]},{},request,env);}
export async function createConnection(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const b=await readJson<Body>(request);const from=requireString(b.fromItemId,'fromItemId',80),to=requireString(b.toItemId,'toItemId',80);if(from===to)throw new HttpError(400,'VALIDATION_ERROR','Connection endpoints must differ.');await ensureItems(env,tripId,[from,to]);const id=uuid(),now=nowMs();const type=enumValue(b.connectionType,'connectionType',types,'unknown');const min=nonNegative(b.minimumBufferMinutes,'minimumBufferMinutes'),rec=nonNegative(b.recommendedBufferMinutes,'recommendedBufferMinutes');await env.DB.prepare(`INSERT INTO connections(id,trip_id,from_item_id,to_item_id,connection_type,minimum_buffer_minutes,recommended_buffer_minutes,requires_baggage_reclaim,requires_immigration,requires_security,requires_terminal_change,requires_airport_change,user_override,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,1)`).bind(id,tripId,from,to,type,min,rec,bool(b.requiresBaggageReclaim),bool(b.requiresImmigration),bool(b.requiresSecurity),bool(b.requiresTerminalChange),bool(b.requiresAirportChange),now,now).run();const connection=await env.DB.prepare(`SELECT * FROM connections WHERE id=?`).bind(id).first();await recordChangeEvent(env,tripId,'connection',id,'connection_added',null,connection);return json({connection},{status:201},request,env);}
export async function updateConnection(request:Request,env:Env,auth:AuthContext,tripId:string,connectionId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const existing=await env.DB.prepare(`SELECT * FROM connections WHERE id=? AND trip_id=?`).bind(connectionId,tripId).first<Record<string,unknown>>();if(!existing)throw new HttpError(404,'CONNECTION_NOT_FOUND','Connection was not found.');const b=await readJson<Body>(request);if(!Number.isSafeInteger(b.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(existing.version!==b.version)throw new HttpError(409,'VERSION_CONFLICT','Connection changed on another client.',{currentVersion:existing.version});const from=b.fromItemId===undefined?String(existing.from_item_id):requireString(b.fromItemId,'fromItemId',80),to=b.toItemId===undefined?String(existing.to_item_id):requireString(b.toItemId,'toItemId',80);if(from===to)throw new HttpError(400,'VALIDATION_ERROR','Connection endpoints must differ.');await ensureItems(env,tripId,[from,to]);const type=b.connectionType===undefined?existing.connection_type as typeof types[number]:enumValue(b.connectionType,'connectionType',types);const min=b.minimumBufferMinutes===undefined?nullableNumber(existing.minimum_buffer_minutes):nonNegative(b.minimumBufferMinutes,'minimumBufferMinutes');const rec=b.recommendedBufferMinutes===undefined?nullableNumber(existing.recommended_buffer_minutes):nonNegative(b.recommendedBufferMinutes,'recommendedBufferMinutes');const now=nowMs();await env.DB.prepare(`UPDATE connections SET from_item_id=?,to_item_id=?,connection_type=?,minimum_buffer_minutes=?,recommended_buffer_minutes=?,requires_baggage_reclaim=?,requires_immigration=?,requires_security=?,requires_terminal_change=?,requires_airport_change=?,user_override=1,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=?`).bind(from,to,type,min,rec,boolPatch(b.requiresBaggageReclaim,existing.requires_baggage_reclaim),boolPatch(b.requiresImmigration,existing.requires_immigration),boolPatch(b.requiresSecurity,existing.requires_security),boolPatch(b.requiresTerminalChange,existing.requires_terminal_change),boolPatch(b.requiresAirportChange,existing.requires_airport_change),now,connectionId,tripId,b.version).run();const connection=await env.DB.prepare(`SELECT * FROM connections WHERE id=?`).bind(connectionId).first();if(!connection||Number((connection as Record<string,unknown>).version)!==Number(b.version)+1)throw new HttpError(409,'VERSION_CONFLICT','Connection changed on another client.');await recordChangeEvent(env,tripId,'connection',connectionId,'connection_updated',existing,connection);return json({connection},{},request,env);}
export async function deleteConnection(request:Request,env:Env,auth:AuthContext,tripId:string,connectionId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const existing=await env.DB.prepare(`SELECT * FROM connections WHERE id=? AND trip_id=?`).bind(connectionId,tripId).first<Record<string,unknown>>();if(!existing)throw new HttpError(404,'CONNECTION_NOT_FOUND','Connection was not found.');const b=await readJson<{version?:unknown}>(request);if(!Number.isSafeInteger(b.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(existing.version!==b.version)throw new HttpError(409,'VERSION_CONFLICT','Connection changed on another client.',{currentVersion:existing.version});const now=nowMs();await env.DB.batch([env.DB.prepare(`INSERT INTO tombstones(entity_type,entity_id,version,deleted_at) VALUES('connection',?,?,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET version=excluded.version,deleted_at=excluded.deleted_at`).bind(connectionId,Number(b.version)+1,now),env.DB.prepare(`DELETE FROM connections WHERE id=? AND trip_id=? AND version=?`).bind(connectionId,tripId,b.version)]);await recordChangeEvent(env,tripId,'connection',connectionId,'connection_removed',existing,{deletedAt:now});return new Response(null,{status:204});}
async function ensureItems(env:Env,tripId:string,ids:string[]){for(const id of ids){const item=await env.DB.prepare(`SELECT 1 AS ok FROM trip_items WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(id,tripId).first();if(!item)throw new HttpError(400,'ITEM_NOT_IN_TRIP','Connection item does not belong to trip.');}}
function nonNegative(v:unknown,n:string):number|null{const x=optionalInteger(v,n);if(x!=null&&x<0)throw new HttpError(400,'VALIDATION_ERROR',`${n} must be >= 0.`);return x;}
function bool(v:unknown):number{if(v==null)return 0;if(typeof v!=='boolean')throw new HttpError(400,'VALIDATION_ERROR','Boolean field is invalid.');return v?1:0;}
function boolPatch(v:unknown,current:unknown):number{if(v===undefined)return Number(current)?1:0;return bool(v);}
function nullableNumber(v:unknown):number|null{return v==null?null:Number(v);}
