import type { AuthContext, Env } from '../types.ts';
import { HttpError, enumValue, json, nowMs, optionalString, readJson, requireString, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

const types=['airline','hotel','driver','host','tour_operator','rental_car','insurance','emergency','other'] as const;
interface Body{contactType?:unknown;displayName?:unknown;localName?:unknown;phone?:unknown;email?:unknown;notes?:unknown;tripItemId?:unknown;travelerId?:unknown;version?:unknown;}

export async function listContacts(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT * FROM trip_contacts WHERE trip_id=? AND deleted_at IS NULL ORDER BY contact_type,display_name`).bind(tripId).all();return json({contacts:r.results??[]},{},request,env);}
export async function createContact(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const body=await readJson<Body>(request);const values=normalize(body);await ensureRefs(env,tripId,values.tripItemId,values.travelerId);const id=uuid(),now=nowMs();await env.DB.prepare(`INSERT INTO trip_contacts(id,trip_id,trip_item_id,traveler_id,contact_type,display_name,local_name,phone,email,notes,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,1)`).bind(id,tripId,values.tripItemId,values.travelerId,values.contactType,values.displayName,values.localName,values.phone,values.email,values.notes,now,now).run();const contact=await env.DB.prepare(`SELECT * FROM trip_contacts WHERE id=?`).bind(id).first();await recordChangeEvent(env,tripId,'trip_contact',id,'contact_created',null,contact);return json({contact},{status:201},request,env);}
export async function updateContact(request:Request,env:Env,auth:AuthContext,tripId:string,contactId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const existing=await env.DB.prepare(`SELECT * FROM trip_contacts WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(contactId,tripId).first<Record<string,unknown>>();if(!existing)throw new HttpError(404,'CONTACT_NOT_FOUND','Contact was not found.');const body=await readJson<Body>(request);if(!Number.isSafeInteger(body.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(existing.version!==body.version)throw new HttpError(409,'VERSION_CONFLICT','Contact changed on another client.',{currentVersion:existing.version});const values=normalize(body,existing);await ensureRefs(env,tripId,values.tripItemId,values.travelerId);const now=nowMs();await env.DB.prepare(`UPDATE trip_contacts SET trip_item_id=?,traveler_id=?,contact_type=?,display_name=?,local_name=?,phone=?,email=?,notes=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(values.tripItemId,values.travelerId,values.contactType,values.displayName,values.localName,values.phone,values.email,values.notes,now,contactId,tripId,body.version).run();const contact=await env.DB.prepare(`SELECT * FROM trip_contacts WHERE id=?`).bind(contactId).first();await recordChangeEvent(env,tripId,'trip_contact',contactId,'contact_updated',existing,contact);return json({contact},{},request,env);}
export async function deleteContact(request:Request,env:Env,auth:AuthContext,tripId:string,contactId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const body=await readJson<{version?:unknown}>(request);if(!Number.isSafeInteger(body.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');const now=nowMs();await env.DB.prepare(`UPDATE trip_contacts SET deleted_at=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(now,now,contactId,tripId,body.version).run();const row=await env.DB.prepare(`SELECT version,deleted_at FROM trip_contacts WHERE id=? AND trip_id=?`).bind(contactId,tripId).first<{version:number;deleted_at:number|null}>();if(!row?.deleted_at)throw new HttpError(409,'VERSION_CONFLICT','Contact changed on another client.');await env.DB.prepare(`INSERT INTO tombstones(entity_type,entity_id,version,deleted_at) VALUES('trip_contact',?,?,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET version=excluded.version,deleted_at=excluded.deleted_at`).bind(contactId,row.version,row.deleted_at).run();await recordChangeEvent(env,tripId,'trip_contact',contactId,'contact_deleted',null,{deletedAt:row.deleted_at});return new Response(null,{status:204});}

function normalize(body:Body,existing:Record<string,unknown>={}){return {contactType:body.contactType===undefined&&existing.contact_type?existing.contact_type as typeof types[number]:enumValue(body.contactType,'contactType',types,'other'),displayName:body.displayName===undefined&&existing.display_name?String(existing.display_name):requireString(body.displayName,'displayName',160),localName:body.localName===undefined?(existing.local_name==null?null:String(existing.local_name)):optionalString(body.localName,'localName',160),phone:body.phone===undefined?(existing.phone==null?null:String(existing.phone)):optionalString(body.phone,'phone',80),email:body.email===undefined?(existing.email==null?null:String(existing.email)):optionalString(body.email,'email',254),notes:body.notes===undefined?(existing.notes==null?null:String(existing.notes)):optionalString(body.notes,'notes',1000),tripItemId:body.tripItemId===undefined?(existing.trip_item_id==null?null:String(existing.trip_item_id)):optionalString(body.tripItemId,'tripItemId',80),travelerId:body.travelerId===undefined?(existing.traveler_id==null?null:String(existing.traveler_id)):optionalString(body.travelerId,'travelerId',80)};}
async function ensureRefs(env:Env,tripId:string,itemId:string|null,travelerId:string|null){if(itemId){const row=await env.DB.prepare(`SELECT 1 AS ok FROM trip_items WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(itemId,tripId).first();if(!row)throw new HttpError(400,'ITEM_NOT_IN_TRIP','Contact booking does not belong to this trip.');}if(travelerId){const row=await env.DB.prepare(`SELECT 1 AS ok FROM travelers WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(travelerId,tripId).first();if(!row)throw new HttpError(400,'TRAVELER_NOT_IN_TRIP','Contact traveler does not belong to this trip.');}}
