import type { AuthContext, Env } from '../types.ts';
import { json, nowMs, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { assessConnection } from '../../../../packages/impact-engine/src/index.ts';
import type { Connection, TripItem } from '../../../../packages/domain/src/index.ts';

interface Row{connection_id:string;from_item_id:string;to_item_id:string;recommended_buffer_minutes:number|null;minimum_buffer_minutes:number|null;connection_type:Connection['type'];from_end:number|null;to_start:number|null;from_status:TripItem['status'];to_status:TripItem['status'];requires_airport_change:number;requires_terminal_change:number;requires_baggage_reclaim:number;requires_immigration:number;requires_security:number;}
export async function recalculateImpacts(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const result=await env.DB.prepare(`SELECT c.id connection_id,c.from_item_id,c.to_item_id,c.recommended_buffer_minutes,c.minimum_buffer_minutes,c.connection_type,a.ends_at_utc from_end,b.starts_at_utc to_start,a.status from_status,b.status to_status,c.requires_airport_change,c.requires_terminal_change,c.requires_baggage_reclaim,c.requires_immigration,c.requires_security FROM connections c JOIN trip_items a ON a.id=c.from_item_id JOIN trip_items b ON b.id=c.to_item_id WHERE c.trip_id=? AND a.deleted_at IS NULL AND b.deleted_at IS NULL`).bind(tripId).all<Row>();const now=nowMs();const impacts=[] as Record<string,unknown>[];for(const row of result.results??[]){const from:TripItem={id:row.from_item_id,tripId,type:'transport',status:row.from_status,title:'Connection origin',endsAtUtc:row.from_end??undefined,confidence:'confirmed'};const to:TripItem={id:row.to_item_id,tripId,type:'transport',status:row.to_status,title:'Connection destination',startsAtUtc:row.to_start??undefined,confidence:'confirmed'};const connection:Connection={id:row.connection_id,fromItemId:row.from_item_id,toItemId:row.to_item_id,type:row.connection_type,recommendedBufferMinutes:row.recommended_buffer_minutes??undefined,minimumBufferMinutes:row.minimum_buffer_minutes??undefined,requiresAirportChange:row.requires_airport_change===1,requiresTerminalChange:row.requires_terminal_change===1,requiresBaggageReclaim:row.requires_baggage_reclaim===1,requiresImmigration:row.requires_immigration===1,requiresSecurity:row.requires_security===1};const assessment=assessConnection(from,to,connection);const impact={connectionId:row.connection_id,itemId:row.to_item_id,availableMinutes:assessment.availableMinutes??null,recommendedMinutes:assessment.requiredMinutes??null,slackMinutes:assessment.bufferMinutes??null,severity:assessment.severity,explanationCode:assessment.explanationCode};impacts.push(impact);await env.DB.prepare(`UPDATE impact_assessments SET status='superseded' WHERE trip_id=? AND item_id=? AND impact_type='connection' AND status='active'`).bind(tripId,row.to_item_id).run();await env.DB.prepare(`INSERT INTO impact_assessments(id,trip_id,item_id,impact_type,severity,assessment_version,status,explanation_code,calculated_at) VALUES (?,?,?,'connection',?,1,'active',?,?)`).bind(uuid(),tripId,row.to_item_id,assessment.severity,assessment.explanationCode,now).run();}return json({impacts,calculatedAt:now},{},request,env);}
export async function listImpacts(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT * FROM impact_assessments WHERE trip_id=? AND status='active' ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END,calculated_at DESC`).bind(tripId).all();return json({impacts:r.results??[]},{},request,env);}
export async function listChanges(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT id,entity_type,entity_id,event_type,source_type,source_id,created_at FROM change_events WHERE trip_id=? ORDER BY created_at DESC LIMIT 200`).bind(tripId).all();return json({changes:r.results??[]},{},request,env);}
