import type { AuthContext, Env } from '../types.ts';
import { HttpError, json, nowMs, optionalString, readJson, requireString, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

interface Body{title?:unknown;propertyName?:unknown;propertyLocationId?:unknown;checkInDate?:unknown;checkInFrom?:unknown;checkInUntil?:unknown;checkOutDate?:unknown;checkOutBy?:unknown;confirmationNumber?:unknown;roomName?:unknown;bookingStatus?:unknown;travelerIds?:unknown;version?:unknown;}
export async function listStays(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const result=await env.DB.prepare(`SELECT ti.id,ti.trip_id,ti.type,ti.status,ti.title,ti.start_location_id,ti.version,ti.created_at,ti.updated_at,s.* FROM trip_items ti JOIN stays s ON s.trip_item_id=ti.id WHERE ti.trip_id=? AND ti.deleted_at IS NULL ORDER BY ti.starts_at_utc,ti.created_at`).bind(tripId).all();return json({stays:result.results??[]},{},request,env);}
export async function createStay(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const b=await readJson<Body>(request);const propertyName=requireString(b.propertyName,'propertyName',160);const title=typeof b.title==='string'&&b.title.trim()?requireString(b.title,'title',160):propertyName;const locationId=optionalString(b.propertyLocationId,'propertyLocationId',80);await ensureLocation(env,tripId,locationId);const checkIn=date(b.checkInDate,'checkInDate');const checkOut=date(b.checkOutDate,'checkOutDate');if(checkIn&&checkOut&&checkOut<checkIn)throw new HttpError(400,'VALIDATION_ERROR','checkOutDate cannot be before checkInDate.');const id=uuid(),now=nowMs();const travelerIds=arrayIds(b.travelerIds);const stmts=[env.DB.prepare(`INSERT INTO trip_items(id,trip_id,type,status,title,start_location_id,source_type,confidence,created_at,updated_at,version) VALUES (?,?,'stay','confirmed',?,?,'manual','confirmed',?,?,1)`).bind(id,tripId,title,locationId,now,now),env.DB.prepare(`INSERT INTO stays(trip_item_id,property_name,property_location_id,check_in_date,check_in_from,check_in_until,check_out_date,check_out_by,confirmation_number,room_name,booking_status) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,propertyName,locationId,checkIn,optionalString(b.checkInFrom,'checkInFrom',20),optionalString(b.checkInUntil,'checkInUntil',20),checkOut,optionalString(b.checkOutBy,'checkOutBy',20),optionalString(b.confirmationNumber,'confirmationNumber',100),optionalString(b.roomName,'roomName',120),optionalString(b.bookingStatus,'bookingStatus',60))];await ensureTravelers(env,tripId,travelerIds);for(const travelerId of travelerIds)stmts.push(env.DB.prepare(`INSERT INTO trip_item_travelers(trip_item_id,traveler_id,role,created_at) VALUES (?,?,'participant',?)`).bind(id,travelerId,now));await env.DB.batch(stmts);const stay=await getStay(env,tripId,id);await recordChangeEvent(env,tripId,'trip_item',id,'stay_added',null,stay);return json({stay},{status:201},request,env);}
export async function updateStay(request:Request,env:Env,auth:AuthContext,tripId:string,itemId:string):Promise<Response>{
 await requireTripAccess(env,auth,tripId,true);const existing=await getStay(env,tripId,itemId);if(!existing)throw new HttpError(404,'STAY_NOT_FOUND','Stay was not found.');const b=await readJson<Body>(request);if(!Number.isSafeInteger(b.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(Number(existing.version)!==b.version)throw new HttpError(409,'VERSION_CONFLICT','Stay changed on another client.',{currentVersion:existing.version});
 const propertyName=b.propertyName===undefined?String(existing.property_name):requireString(b.propertyName,'propertyName',160);const title=b.title===undefined?String(existing.title):(typeof b.title==='string'&&b.title.trim()?requireString(b.title,'title',160):propertyName);const locationId=b.propertyLocationId===undefined?nullableString(existing.property_location_id):optionalString(b.propertyLocationId,'propertyLocationId',80);await ensureLocation(env,tripId,locationId);const checkIn=b.checkInDate===undefined?nullableString(existing.check_in_date):date(b.checkInDate,'checkInDate');const checkOut=b.checkOutDate===undefined?nullableString(existing.check_out_date):date(b.checkOutDate,'checkOutDate');if(checkIn&&checkOut&&checkOut<checkIn)throw new HttpError(400,'VALIDATION_ERROR','checkOutDate cannot be before checkInDate.');const now=nowMs();
 await env.DB.batch([env.DB.prepare(`UPDATE stays SET property_name=?,property_location_id=?,check_in_date=?,check_in_from=?,check_in_until=?,check_out_date=?,check_out_by=?,confirmation_number=?,room_name=?,booking_status=? WHERE trip_item_id=? AND EXISTS (SELECT 1 FROM trip_items WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL)`).bind(propertyName,locationId,checkIn,b.checkInFrom===undefined?nullableString(existing.check_in_from):optionalString(b.checkInFrom,'checkInFrom',20),b.checkInUntil===undefined?nullableString(existing.check_in_until):optionalString(b.checkInUntil,'checkInUntil',20),checkOut,b.checkOutBy===undefined?nullableString(existing.check_out_by):optionalString(b.checkOutBy,'checkOutBy',20),b.confirmationNumber===undefined?nullableString(existing.confirmation_number):optionalString(b.confirmationNumber,'confirmationNumber',100),b.roomName===undefined?nullableString(existing.room_name):optionalString(b.roomName,'roomName',120),b.bookingStatus===undefined?nullableString(existing.booking_status):optionalString(b.bookingStatus,'bookingStatus',60),itemId,itemId,tripId,b.version),env.DB.prepare(`UPDATE trip_items SET title=?,start_location_id=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(title,locationId,now,itemId,tripId,b.version)]);
 const stay=await getStay(env,tripId,itemId);if(!stay||Number(stay.version)!==Number(b.version)+1)throw new HttpError(409,'VERSION_CONFLICT','Stay changed on another client.');await recordChangeEvent(env,tripId,'trip_item',itemId,'stay_updated',existing,stay);return json({stay},{},request,env);
}
export async function deleteStay(request:Request,env:Env,auth:AuthContext,tripId:string,itemId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const existing=await getStay(env,tripId,itemId);if(!existing)throw new HttpError(404,'STAY_NOT_FOUND','Stay was not found.');const b=await readJson<{version?:unknown}>(request);if(!Number.isSafeInteger(b.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(Number(existing.version)!==b.version)throw new HttpError(409,'VERSION_CONFLICT','Stay changed on another client.',{currentVersion:existing.version});const now=nowMs();await env.DB.prepare(`UPDATE trip_items SET deleted_at=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(now,now,itemId,tripId,b.version).run();const row=await env.DB.prepare(`SELECT version,deleted_at FROM trip_items WHERE id=? AND trip_id=?`).bind(itemId,tripId).first<{version:number;deleted_at:number|null}>();if(!row?.deleted_at)throw new HttpError(409,'VERSION_CONFLICT','Stay changed on another client.');await env.DB.prepare(`INSERT INTO tombstones(entity_type,entity_id,version,deleted_at) VALUES('trip_item',?,?,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET version=excluded.version,deleted_at=excluded.deleted_at`).bind(itemId,row.version,row.deleted_at).run();await recordChangeEvent(env,tripId,'trip_item',itemId,'stay_removed',existing,{deletedAt:row.deleted_at});return new Response(null,{status:204});}
async function getStay(env:Env,tripId:string,itemId:string):Promise<Record<string,unknown>|null>{return env.DB.prepare(`SELECT ti.id,ti.trip_id,ti.status,ti.title,ti.start_location_id,ti.version,ti.deleted_at,s.* FROM trip_items ti JOIN stays s ON s.trip_item_id=ti.id WHERE ti.trip_id=? AND ti.id=? AND ti.deleted_at IS NULL`).bind(tripId,itemId).first<Record<string,unknown>>();}
async function ensureLocation(env:Env,tripId:string,id:string|null){if(!id)return;const ok=await env.DB.prepare(`SELECT 1 AS ok FROM trip_locations WHERE trip_id=? AND location_id=?`).bind(tripId,id).first();if(!ok)throw new HttpError(400,'LOCATION_NOT_IN_TRIP','Location does not belong to this trip.');}
async function ensureTravelers(env:Env,tripId:string,ids:string[]){for(const id of ids){const t=await env.DB.prepare(`SELECT 1 AS ok FROM travelers WHERE trip_id=? AND id=? AND deleted_at IS NULL`).bind(tripId,id).first();if(!t)throw new HttpError(400,'TRAVELER_NOT_IN_TRIP','Traveler does not belong to this trip.');}}
function date(v:unknown,n:string):string|null{const s=optionalString(v,n,10);if(s==null)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new HttpError(400,'VALIDATION_ERROR',`${n} must be YYYY-MM-DD.`);return s;}
function arrayIds(v:unknown):string[]{if(v==null)return[];if(!Array.isArray(v)||v.length>20||v.some(x=>typeof x!=='string'||!x))throw new HttpError(400,'VALIDATION_ERROR','travelerIds must be an array of IDs.');return [...new Set(v as string[])];}
function nullableString(v:unknown):string|null{return v==null?null:String(v);}
