import type { AuthContext, Env } from '../types.ts';
import { HttpError, json, nowMs, optionalString, readJson, requireString, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

interface Body{title?:unknown;propertyName?:unknown;propertyLocationId?:unknown;checkInDate?:unknown;checkInFrom?:unknown;checkInUntil?:unknown;checkOutDate?:unknown;checkOutBy?:unknown;confirmationNumber?:unknown;roomName?:unknown;bookingStatus?:unknown;travelerIds?:unknown;}
export async function listStays(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const result=await env.DB.prepare(`SELECT ti.*,s.* FROM trip_items ti JOIN stays s ON s.trip_item_id=ti.id WHERE ti.trip_id=? AND ti.deleted_at IS NULL ORDER BY ti.starts_at_utc,ti.created_at`).bind(tripId).all();return json({stays:result.results??[]},{},request,env);}
export async function createStay(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const b=await readJson<Body>(request);const propertyName=requireString(b.propertyName,'propertyName',160);const title=typeof b.title==='string'&&b.title.trim()?requireString(b.title,'title',160):propertyName;const locationId=optionalString(b.propertyLocationId,'propertyLocationId',80);if(locationId){const ok=await env.DB.prepare(`SELECT 1 AS ok FROM trip_locations WHERE trip_id=? AND location_id=?`).bind(tripId,locationId).first();if(!ok)throw new HttpError(400,'LOCATION_NOT_IN_TRIP','Location does not belong to this trip.');}const checkIn=date(b.checkInDate,'checkInDate');const checkOut=date(b.checkOutDate,'checkOutDate');if(checkIn&&checkOut&&checkOut<checkIn)throw new HttpError(400,'VALIDATION_ERROR','checkOutDate cannot be before checkInDate.');const id=uuid(),now=nowMs();const travelerIds=arrayIds(b.travelerIds);const stmts=[env.DB.prepare(`INSERT INTO trip_items(id,trip_id,type,status,title,start_location_id,source_type,confidence,created_at,updated_at,version) VALUES (?,?,'stay','confirmed',?,?,'manual','confirmed',?,?,1)`).bind(id,tripId,title,locationId,now,now),env.DB.prepare(`INSERT INTO stays(trip_item_id,property_name,property_location_id,check_in_date,check_in_from,check_in_until,check_out_date,check_out_by,confirmation_number,room_name,booking_status) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,propertyName,locationId,checkIn,optionalString(b.checkInFrom,'checkInFrom',20),optionalString(b.checkInUntil,'checkInUntil',20),checkOut,optionalString(b.checkOutBy,'checkOutBy',20),optionalString(b.confirmationNumber,'confirmationNumber',100),optionalString(b.roomName,'roomName',120),optionalString(b.bookingStatus,'bookingStatus',60))];for(const travelerId of travelerIds){const t=await env.DB.prepare(`SELECT 1 AS ok FROM travelers WHERE trip_id=? AND id=? AND deleted_at IS NULL`).bind(tripId,travelerId).first();if(!t)throw new HttpError(400,'TRAVELER_NOT_IN_TRIP','Traveler does not belong to this trip.');stmts.push(env.DB.prepare(`INSERT INTO trip_item_travelers(trip_item_id,traveler_id,role,created_at) VALUES (?,?,'participant',?)`).bind(id,travelerId,now));}await env.DB.batch(stmts);const stay=await env.DB.prepare(`SELECT ti.*,s.* FROM trip_items ti JOIN stays s ON s.trip_item_id=ti.id WHERE ti.id=?`).bind(id).first();await recordChangeEvent(env,tripId,'trip_item',id,'stay_added',null,stay);return json({stay},{status:201},request,env);}
function date(v:unknown,n:string):string|null{const s=optionalString(v,n,10);if(s==null)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new HttpError(400,'VALIDATION_ERROR',`${n} must be YYYY-MM-DD.`);return s;}
function arrayIds(v:unknown):string[]{if(v==null)return[];if(!Array.isArray(v)||v.length>20||v.some(x=>typeof x!=='string'||!x))throw new HttpError(400,'VALIDATION_ERROR','travelerIds must be an array of IDs.');return [...new Set(v as string[])];}
