import type { AuthContext, Env } from '../types.ts';
import { HttpError, enumValue, json, nowMs, optionalInteger, optionalString, readJson, uuid } from '../http.ts';
import { requireTripAccess } from '../access.ts';
import { recordChangeEvent } from '../change-events.ts';

const markerTypes=['boarding','gate_close','check_in_open','check_in_close','reservation_window_start','reservation_window_end','arrival_deadline','pickup_deadline','document_deadline','other'] as const;
const confidences=['confirmed','live','estimated','unavailable','low_confidence'] as const;
const sources=['manual','email','upload','system','provider'] as const;
interface Body{tripItemId?:unknown;markerType?:unknown;label?:unknown;atUtc?:unknown;localDatetime?:unknown;timezone?:unknown;confidence?:unknown;sourceType?:unknown;notes?:unknown;version?:unknown;}

export async function listTimeMarkers(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId);const r=await env.DB.prepare(`SELECT tm.*,ti.title AS item_title FROM trip_time_markers tm LEFT JOIN trip_items ti ON ti.id=tm.trip_item_id WHERE tm.trip_id=? AND tm.deleted_at IS NULL ORDER BY COALESCE(tm.at_utc,9223372036854775807),tm.created_at`).bind(tripId).all();return json({timeMarkers:r.results??[]},{},request,env);}
export async function createTimeMarker(request:Request,env:Env,auth:AuthContext,tripId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const body=await readJson<Body>(request);const values=normalize(body);await ensureItem(env,tripId,values.tripItemId);const id=uuid(),now=nowMs();await env.DB.prepare(`INSERT INTO trip_time_markers(id,trip_id,trip_item_id,marker_type,label,at_utc,local_datetime,timezone,confidence,source_type,notes,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1)`).bind(id,tripId,values.tripItemId,values.markerType,values.label,values.atUtc,values.localDatetime,values.timezone,values.confidence,values.sourceType,values.notes,now,now).run();const marker=await env.DB.prepare(`SELECT * FROM trip_time_markers WHERE id=?`).bind(id).first();await recordChangeEvent(env,tripId,'trip_time_marker',id,'time_marker_created',null,marker);return json({timeMarker:marker},{status:201},request,env);}
export async function updateTimeMarker(request:Request,env:Env,auth:AuthContext,tripId:string,markerId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const existing=await env.DB.prepare(`SELECT * FROM trip_time_markers WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(markerId,tripId).first<Record<string,unknown>>();if(!existing)throw new HttpError(404,'TIME_MARKER_NOT_FOUND','Time marker was not found.');const body=await readJson<Body>(request);if(!Number.isSafeInteger(body.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');if(existing.version!==body.version)throw new HttpError(409,'VERSION_CONFLICT','Time marker changed on another client.',{currentVersion:existing.version});const values=normalize(body,existing);await ensureItem(env,tripId,values.tripItemId);const now=nowMs();await env.DB.prepare(`UPDATE trip_time_markers SET trip_item_id=?,marker_type=?,label=?,at_utc=?,local_datetime=?,timezone=?,confidence=?,source_type=?,notes=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(values.tripItemId,values.markerType,values.label,values.atUtc,values.localDatetime,values.timezone,values.confidence,values.sourceType,values.notes,now,markerId,tripId,body.version).run();const marker=await env.DB.prepare(`SELECT * FROM trip_time_markers WHERE id=?`).bind(markerId).first();await recordChangeEvent(env,tripId,'trip_time_marker',markerId,'time_marker_updated',existing,marker);return json({timeMarker:marker},{},request,env);}
export async function deleteTimeMarker(request:Request,env:Env,auth:AuthContext,tripId:string,markerId:string):Promise<Response>{await requireTripAccess(env,auth,tripId,true);const body=await readJson<{version?:unknown}>(request);if(!Number.isSafeInteger(body.version))throw new HttpError(400,'VERSION_REQUIRED','Current entity version is required.');const now=nowMs();await env.DB.prepare(`UPDATE trip_time_markers SET deleted_at=?,updated_at=?,version=version+1 WHERE id=? AND trip_id=? AND version=? AND deleted_at IS NULL`).bind(now,now,markerId,tripId,body.version).run();const row=await env.DB.prepare(`SELECT version,deleted_at FROM trip_time_markers WHERE id=? AND trip_id=?`).bind(markerId,tripId).first<{version:number;deleted_at:number|null}>();if(!row?.deleted_at)throw new HttpError(409,'VERSION_CONFLICT','Time marker changed on another client.');await env.DB.prepare(`INSERT INTO tombstones(entity_type,entity_id,version,deleted_at) VALUES('trip_time_marker',?,?,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET version=excluded.version,deleted_at=excluded.deleted_at`).bind(markerId,row.version,row.deleted_at).run();await recordChangeEvent(env,tripId,'trip_time_marker',markerId,'time_marker_deleted',null,{deletedAt:row.deleted_at});return new Response(null,{status:204});}

function normalize(body:Body,existing:Record<string,unknown>={}){const atUtc=body.atUtc===undefined?(existing.at_utc==null?null:Number(existing.at_utc)):optionalInteger(body.atUtc,'atUtc');const localDatetime=body.localDatetime===undefined?(existing.local_datetime==null?null:String(existing.local_datetime)):optionalString(body.localDatetime,'localDatetime',40);if(atUtc==null&&!localDatetime)throw new HttpError(400,'VALIDATION_ERROR','atUtc or localDatetime is required.');return {tripItemId:body.tripItemId===undefined?(existing.trip_item_id==null?null:String(existing.trip_item_id)):optionalString(body.tripItemId,'tripItemId',80),markerType:body.markerType===undefined&&existing.marker_type?existing.marker_type as typeof markerTypes[number]:enumValue(body.markerType,'markerType',markerTypes),label:body.label===undefined?(existing.label==null?null:String(existing.label)):optionalString(body.label,'label',120),atUtc,localDatetime,timezone:body.timezone===undefined?(existing.timezone==null?null:String(existing.timezone)):optionalString(body.timezone,'timezone',80),confidence:body.confidence===undefined&&existing.confidence?existing.confidence as typeof confidences[number]:enumValue(body.confidence,'confidence',confidences,'confirmed'),sourceType:body.sourceType===undefined&&existing.source_type?existing.source_type as typeof sources[number]:enumValue(body.sourceType,'sourceType',sources,'manual'),notes:body.notes===undefined?(existing.notes==null?null:String(existing.notes)):optionalString(body.notes,'notes',1000)};}
async function ensureItem(env:Env,tripId:string,id:string|null){if(!id)return;const row=await env.DB.prepare(`SELECT 1 AS ok FROM trip_items WHERE id=? AND trip_id=? AND deleted_at IS NULL`).bind(id,tripId).first();if(!row)throw new HttpError(400,'ITEM_NOT_IN_TRIP','Time marker item does not belong to this trip.');}
