from PIL import Image,ImageDraw
root=(AUDIT_OUTPUT/'states')
fixture=(SUITE_DIR/'fixture.js').read_text()
cases=[]
def add(name,screen,id=None,setup='',clicks=()): cases.append((name,screen,id,setup,clicks))
add('collection','collection','audit-neighborhood')
add('collection-empty','collection','audit-neighborhood','s.collectionStops=[]')
add('collection-long','collection','audit-neighborhood','s.collections[0].title="An extended morning visiting the neighborhood and its historic streets";s.collectionStops[0].title="Museum of history, architecture, photography and contemporary art — a long local place name";s.collectionStops[0].notes="A longer description, including accessibility arrangements and time for a break before the next booking.";s.collectionStops[0].address_snapshot="Via di San Francesco a Ripa, Trastevere, Roma, Italia";')
add('collection-edit','collection','audit-neighborhood','',('[data-action="edit-collection"]',))
add('stop-new','collection','audit-neighborhood','',('[data-action="collection-add-place"]',))
add('stop-edit','collection','audit-neighborhood','',('[data-action="stop-menu"][data-id="audit-stop-2"]','[data-action="edit-stop"]'))
add('ideas','save-later')
add('idea-day-picker','save-later',None,'',('[data-action="open-idea"]','[data-action="idea-add-to-plan"]'))
add('idea-no-trip-dates','save-later',None,'s.trip.starts_on=s.trip.ends_on=null;',('[data-action="open-idea"]','[data-action="idea-add-to-plan"]'))
add('ideas-planned-empty','save-later',None,'',('[data-action="save-later-filter"][data-filter="planned"]',))
add('planning-populated','planning')
add('collab-owner','collaboration')
add('collab-editor','collaboration',None,'s.trip.role="editor";s.sharing.role="editor";s.sharing.canManage=false;')
add('collab-viewer','collaboration',None,'s.trip.role="viewer";s.sharing.role="viewer";s.sharing.canManage=false;')
add('collab-disabled','collaboration',None,'s.sharing.enabled=false;')
add('collab-error','collaboration',None,'s.collabError="Connection interrupted. Your trip remains saved. Try again when connected.";')
add('collab-loading','collaboration',None,'s.collabLoading=true;')
add('collab-empty','collaboration',None,'s.members=[];s.invites=[];')
add('share-link-ready','collaboration',None,'s.shareInvite={inviteUrl:"https://example.test/join/local-audit-token-not-a-real-invitation",role:"viewer",expiresAt:new Date(Date.now()+86400000).toISOString()};',('[data-action="open-share"]',))
add('share-busy','collaboration',None,'s.shareBusy=true;',('[data-action="open-share"]',))
add('leave-confirm','collaboration',None,'s.trip.role="editor";s.sharing.role="editor";s.sharing.canManage=false;',('[data-action="leave-trip"]',))
for name,settings in [('join-valid',''),('join-guest','s.account={mode:"guest"};'),('join-paused','s.joinPreview.sharingEnabled=false;'),('join-expired','s.joinPreview=null;s.joinError="This invitation has expired. Ask the owner for a new link.";'),('join-busy','s.joinLoading=true;')]:
 add(name,'join','audit-token','s.joinCheckedToken="audit-token";s.joinPreview={tripTitle:"Rome with friends",role:"editor",sharingEnabled:true};s.joinLoading=false;s.joinError=null;'+settings)
add('join-missing','join',None,'s.joinToken=null;s.joinPreview=null;')
add('email-populated','booking-email-inbox')
add('email-trip-picker','booking-email-inbox',None,'',('[data-action="choose-booking-email-trip"]',))
add('documents-empty','documents',None,'s.localDocs=[];')
add('bookings-empty','bookings',None,'s.timeline=[];s.transport=[];s.stays=[];')
add('travelers-empty','travelers',None,'s.travelers=[];')
add('checklist-empty','checklist',None,'s.checklist=[];')
add('document-sheet','documents',None,'',('[data-action="document-sheet"]',))
add('flight-expanded','flight','flight','',('[data-action="toggle-flight-details"]',))
add('flight-edit','flight','flight','',('[data-action="manage-booking"]','[data-action="edit-booking"]'))
add('hotel-edit','hotel','stay','',('[data-action="manage-booking"]','[data-action="edit-booking"]'))
add('train-edit','train','train','',('[data-action="manage-booking"]','[data-action="edit-booking"]'))
add('activity-edit','plan','activity','',('[data-action="manage-booking"]','[data-action="edit-booking"]'))
add('trip-edit','trip-options',None,'',('[data-action="edit-trip"]',))
add('traveler-edit','traveler','traveler','',('[data-action="open-form"]',))
add('driver-final','hotel','stay','',('[data-action="show-driver"]',))
add('missing-plan','plan','absent-id')
add('missing-traveler','traveler','absent-id')
add('import-empty','import-review','audit-import','s.importReview={candidates:[],warnings:["This document contains no supported booking details."]};')
add('import-candidate','import-review','audit-import','s.importReview={candidates:[{id:"audit-candidate",type:"hotel",confidence:0.95,payload:{propertyName:"Hotel from local QA fixture",checkInDate:s.trip.starts_on,checkOutDate:s.trip.ends_on,address:"Local preview address",confirmationNumber:"QA-123"}}]};')
add('import-duplicate','import-review','audit-import','s.importReview={duplicate:true,candidates:[{id:"audit-candidate",type:"flight",confidence:0.7,payload:{airlineCode:"LY",flightNumber:"383",departureIata:"TLV",arrivalIata:"FCO",departureLocalDatetime:s.trip.starts_on+"T10:00",arrivalLocalDatetime:s.trip.starts_on+"T12:30",departureTimezone:"Asia/Jerusalem",arrivalTimezone:"Europe/Rome"},warnings:["Review the departure time before adding."]}]};')
records=[];start=int(sys.argv[4]) if len(sys.argv)>4 else 0;end=int(sys.argv[5]) if len(sys.argv)>5 else len(cases)
for name,screen,id,setup,clicks in cases[start:end]:
 try:
  b.nav();b.js(fixture)
  if setup:b.js('(()=>{const s=TriptoMobileApp.getState();'+setup+'})()')
  b.js('TriptoMobileApp.show('+json.dumps(screen)+','+json.dumps(id)+',true)');time.sleep(.2)
  for sel in clicks:b.click(sel)
  data=b.inspect();shots=[]
  b.screenshot(root/(name+'-top.png'));shots.append(name+'-top.png')
  n=b.js('document.querySelectorAll("main,.sheet-scroll,.collection-timeline-scroll").length')
  for i in range(n):
   h,sh=b.js(f'(()=>{{const e=document.querySelectorAll("main,.sheet-scroll,.collection-timeline-scroll")[{i}];return [e.clientHeight,e.scrollHeight]}})()')
   if h<1 or sh<=h+2:continue
   for j,y in enumerate(range(max(1,h-50),sh,max(1,h-50))):
    b.js(f'document.querySelectorAll("main,.sheet-scroll,.collection-timeline-scroll")[{i}].scrollTop={y}')
    file=f'{name}-scroll-{i}-{j}.png';b.screenshot(root/file);shots.append(file)
  data['evidence']=shots;data['fixtureSetup']=setup;data['trigger']=clicks
  (root/(name+'.json')).write_text(json.dumps(data,indent=2));records.append((name,shots));print(name,data['screen'],'OVERFLOW' if data['overflow'] else '',flush=True)
  b.cmd('Input.dispatchKeyEvent',{'type':'keyDown','key':'Escape','code':'Escape','windowsVirtualKeyCode':27})
 except Exception as e:print(name,'ERROR',str(e)[:220],flush=True);root.mkdir(parents=True,exist_ok=True);(root/(name+'-error.txt')).write_text(str(e));raise
for i in range(0,len(records),4):
 batch=records[i:i+4];canvas=Image.new('RGB',(390*len(batch),1718),'#ddd');draw=ImageDraw.Draw(canvas)
 for x,(name,shots) in enumerate(batch):
  draw.text((390*x+5,8),name,fill='black');canvas.paste(Image.open(root/shots[0]),(390*x,30));canvas.paste(Image.open(root/shots[-1]),(390*x,874))
 canvas.save(root/f'contact-{start+i}.png')
