-- Worldwide Tax Free research ledger and reviewed country-rule expansion.

-- A screening result is evidence of research, not evidence that a refund is unavailable.


CREATE TABLE IF NOT EXISTS tax_free_research_checks (
    id TEXT PRIMARY KEY,
    territory_id TEXT NOT NULL REFERENCES tax_free_territories(id) ON DELETE CASCADE,
    result TEXT NOT NULL CHECK (result IN ('official_available','official_unavailable','official_partial','operator_evidence','global_screen_no_conclusion')),
    source_url TEXT NOT NULL,
    publisher TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('tax_authority','customs','airport','law','operator','professional_tax_guide')),
    finding_summary TEXT NOT NULL,
    checked_at INTEGER NOT NULL,
    next_review_at INTEGER,
    UNIQUE(territory_id, source_url)
  );

CREATE INDEX IF NOT EXISTS idx_tax_free_research_territory ON tax_free_research_checks(territory_id, result, checked_at);

INSERT OR IGNORE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at)
   SELECT 'tf-research-global-' || lower(country_code),id,'global_screen_no_conclusion',
    'https://taxsummaries.pwc.com/quick-charts/value-added-tax-vat-rates','PwC Worldwide Tax Summaries','professional_tax_guide',
    'Worldwide VAT/GST table screened. This cross-country source does not establish whether a traveler refund operates in this territory; country-authority confirmation is still required.',
    1790467200000,1806278400000
   FROM tax_free_territories WHERE region_code IS NULL;

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-je','tf-je','official_available','https://www.gov.je/taxesmoney/gst/gstcustomers/pages/gstrefundsvisitors.aspx','Government of Jersey','tax_authority','Eligibility, £100 threshold, one-month deadline, exclusions and validation locations',1790467200000,1806278400000);

UPDATE tax_free_rule_versions SET lifecycle='retired',effective_to='2026-09-26',updated_at=1790467200000 WHERE territory_id='tf-je' AND lifecycle='published';

UPDATE tax_free_territories SET status='verified_available',regional_note='The official visitor scheme rules are verified. Kiosk opening hours are not published on the government page, so confirm access before departure.',updated_at=1790467200000 WHERE id='tf-je';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-je-research-v2','tf-je',2,'published','available','GST visitor refund scheme','Eligible visitors can reclaim Jersey GST on qualifying goods bought from an approved retailer and exported on a scheduled commercial flight or ferry.','["Not resident in Jersey","Present in Jersey for no more than 60 days in the calendar year","At least 16 years old","Not a crew member on the departing flight"]','["More than £100 with one approved retailer on the same day","Goods must carry GST and come from an approved retailer","Services, consumed goods, tobacco, vapes and fuel are excluded"]','["Confirm that the retailer participates","Complete the approved online Global Blue tax-free form","Keep the original payment receipts"]','["Passport or approved identity document","Original payment receipts","Global Blue tax-free record"]','["Take the goods out of Jersey","Keep goods available for any requested export check","Do not consume eligible goods before departure"]','{"export":"Leave Jersey with the goods within one month of purchase"}','["Validate export at a Global Blue kiosk after security at Jersey Airport or in the Elizabeth ferry terminal"]','["Use the Global Blue kiosk with identity documents and original receipts"]','["Global Blue processes the refund under the approved scheme","Operator charges may reduce the amount paid"]','The official visitor scheme rules are verified. Kiosk opening hours are not published on the government page, so confirm access before departure.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review','tf-je-world-v1',1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-je-research','tf-je-research-v2','https://www.gov.je/taxesmoney/gst/gstcustomers/pages/gstrefundsvisitors.aspx','www.gov.je','Government of Jersey','tax_authority','Eligibility, £100 threshold, one-month deadline, exclusions and validation locations',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-je-research','tf-je-research-v2','Standard GST',5,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-je-research','tf-je-research-v2','Published minimum',100,NULL,'JEP','store_day','gt','More than £100 with one approved retailer on the same day.');

INSERT OR IGNORE INTO tax_free_departure_points (id,rule_version_id,location_type,location_code,location_name,city,timezone,terminal,zone,service_type,operator_name,hours_status,hours_json,location_details,before_security,instruction_codes_json,baggage_code,contact_json,map_url,source_id,content_verified_at,source_checked_at,active) VALUES ('tf-point-je-jer-research','tf-je-research-v2','airport','JER','Jersey Airport','Jersey','Europe/Jersey','Departures','Global Blue kiosk after security','combined','Global Blue','not_published','{"kind":"not_published"}','Use the Global Blue kiosk after security with your passport or approved ID and original payment receipts.',0,'["arrive_early","show_documents_goods","validation_before_payment"]','keep_accessible',NULL,NULL,'tf-src-je-research',1790467200000,1790467200000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-je-research-v2','tf-je','tf-je-research-v2','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-pe','tf-pe','official_available','https://emprender.sunat.gob.pe/principales-impuestos/imp-general-las-ventas-igv/tax-free','SUNAT','tax_authority','Current eligibility, purchase rules, Lima kiosk location, payout and 2025 operational update',1790467200000,1806278400000);

UPDATE tax_free_rule_versions SET lifecycle='retired',effective_to='2026-09-26',updated_at=1790467200000 WHERE territory_id='tf-pe' AND lifecycle='published';

UPDATE tax_free_territories SET status='verified_available',regional_note='SUNAT publishes the operational process and Lima airport location. Confirm the authorized-store list and current operator terms before purchase.',updated_at=1790467200000 WHERE id='tf-pe';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-pe-research-v2','tf-pe',2,'published','available','Tourist IGV refund — Tax Free Peru','Foreign non-domiciled tourists staying 2 to 60 days can request an IGV refund for qualifying goods bought in person from authorized establishments.','["Foreign individual not domiciled in Peru","Entered Peru as a tourist","Stay is at least 2 and no more than 60 calendar days per entry"]','["Goods bought in person from an authorized establishment","At least PEN 100 per qualifying purchase","Services do not qualify","Payment must use an internationally valid card in the tourist''s name"]','["State that you intend to claim before the invoice is issued","Obtain a Tax Free invoice and certificate","Keep the goods with you for export"]','["Travel identity document","Tax Free invoice","Tax Free certificate","Eligible debit or credit card in the tourist''s name"]','["The tourist who bought the goods must personally take them out of Peru"]','{"application":"Submit the request before the authorized stay in Peru ends","payment":"The collaborating entity states payment within five calendar days after a valid request"}','["Complete the departure validation assigned by the self-service kiosk or mobile application","Present goods when the system assigns the inspection channel"]','["Use the self-service module in the pre-boarding control area on the third floor of the new Jorge Chávez terminal or the supported mobile application"]','["Refund is credited to the registered debit or credit card","The collaborating entity may deduct a disclosed service fee"]','SUNAT publishes the operational process and Lima airport location. Confirm the authorized-store list and current operator terms before purchase.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review','tf-pe-world-v1',1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-pe-research','tf-pe-research-v2','https://emprender.sunat.gob.pe/principales-impuestos/imp-general-las-ventas-igv/tax-free','emprender.sunat.gob.pe','SUNAT','tax_authority','Current eligibility, purchase rules, Lima kiosk location, payout and 2025 operational update',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-pe-research','tf-pe-research-v2','Standard IGV',18,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-pe-research','tf-pe-research-v2','Minimum purchase',100,NULL,'PEN','item','gte','The official traveler guide states a minimum purchase of PEN 100.');

INSERT OR IGNORE INTO tax_free_departure_points (id,rule_version_id,location_type,location_code,location_name,city,timezone,terminal,zone,service_type,operator_name,hours_status,hours_json,location_details,before_security,instruction_codes_json,baggage_code,contact_json,map_url,source_id,content_verified_at,source_checked_at,active) VALUES ('tf-point-pe-lim-research','tf-pe-research-v2','airport','LIM','Jorge Chávez International Airport','Lima','America/Lima','New terminal · third floor','Pre-boarding control area self-service module','combined','Global Blue Perú','not_published','{"kind":"not_published"}','Use the self-service module or supported mobile application. The system may assign a green or red inspection channel.',1,'["before_checkin","show_documents_goods","validation_before_payment"]','hold_before_checkin',NULL,NULL,'tf-src-pe-research',1790467200000,1790467200000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-pe-research-v2','tf-pe','tf-pe-research-v2','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-ch','tf-ch','official_available','https://www.estv.admin.ch/en/tax-free-for-tourists','Swiss Federal Tax Administration','tax_authority','Eligibility, CHF 300 threshold, export documentation and responsibility for repayment',1790467200000,1806278400000);

UPDATE tax_free_rule_versions SET lifecycle='retired',effective_to='2026-09-26',updated_at=1790467200000 WHERE territory_id='tf-ch' AND lifecycle='published';

UPDATE tax_free_territories SET status='verified_available',regional_note='The legal conditions are verified. Refund handling is a private-law matter with the seller, and airport desk hours can vary.',updated_at=1790467200000 WHERE id='tf-ch';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-ch-research-v2','tf-ch',2,'published','available','Tax-free for tourists','A supplier can exempt or refund Swiss VAT when a visitor domiciled abroad exports qualifying retail goods and obtains the required export confirmation.','["Domiciled outside Switzerland","Buyer is the person named on the export document"]','["Retail price is at least CHF 300 including VAT","Goods are exported in tourist traffic"]','["Ask the supplier for the export document","Confirm how the supplier or refund operator will pay after export proof"]','["Official identity document","Purchase receipt","Swiss export document"]','["Carry the qualifying goods out of Switzerland and keep them available for customs confirmation"]','{"export":"Export and customs confirmation within 90 days of purchase"}','["Obtain export confirmation when leaving Swiss territory"]','[]','["The supplier or its refund operator handles repayment","Swiss tax and customs authorities do not pay the traveler directly"]','The legal conditions are verified. Refund handling is a private-law matter with the seller, and airport desk hours can vary.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review','tf-ch-world-v1',1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-ch-research','tf-ch-research-v2','https://www.estv.admin.ch/en/tax-free-for-tourists','www.estv.admin.ch','Swiss Federal Tax Administration','tax_authority','Eligibility, CHF 300 threshold, export documentation and responsibility for repayment',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-ch-research','tf-ch-research-v2','Standard VAT',8.1,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-ch-research','tf-ch-research-v2','Published minimum',300,NULL,'CHF','receipt','gte','Minimum retail price including VAT.');

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-ch-gva-research','tf-ch-research-v2','https://www.gva.ch/en/passengers/travel-preparation/services/our-services/tax-vat-refund','www.gva.ch','Geneva Airport','airport','Geneva Airport refund flow and service counters',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_departure_points (id,rule_version_id,location_type,location_code,location_name,city,timezone,terminal,zone,service_type,operator_name,hours_status,hours_json,location_details,before_security,instruction_codes_json,baggage_code,contact_json,map_url,source_id,content_verified_at,source_checked_at,active) VALUES ('tf-point-ch-gva-research','tf-ch-research-v2','airport','GVA','Geneva Airport','Geneva','Europe/Zurich','Departures','Customs validation followed by Change Helvetic or Tax Refund / VAT Refund desk','combined','Change Helvetic','not_published','{"kind":"not_published"}','First obtain customs validation, then use the refund counter for an eligible cash or card payment.',1,'["arrive_early","show_documents_goods","validation_before_payment"]','hold_before_checkin',NULL,NULL,'tf-src-ch-gva-research',1790467200000,1790467200000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-ch-research-v2','tf-ch','tf-ch-research-v2','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-am','tf-am','official_available','https://www.arlis.am/en/acts/181106','Armenian Legal Information System','law','Eligibility, AMD 50,000 threshold, 90-day export deadline and exclusions',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='verified_available',regional_note='The government decision and 2023 amendments are verified. Exact counter locations and hours depend on the departure point and are not published in this record.',updated_at=1790467200000 WHERE id='tf-am';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-am-research-v1','tf-am',1,'published','available','VAT refund for foreign visitors','Armenia refunds VAT to foreign citizens and stateless persons who export qualifying unused goods under the government procedure.','["Foreign citizen or stateless person","Buyer named on the VAT refund tax invoice"]','["At least AMD 50,000 including VAT from the same taxpayer in one calendar day","Food, tobacco, medicines, cultural property and vehicles are excluded"]','["Request the VAT refund tax invoice and check the personal and purchase details"]','["Passport or travel identity document","VAT refund tax invoice","Purchase documentation"]','["Goods must be unused and retain factory packaging or labeling","Present goods for export verification"]','{"export":"Export within 90 days after purchase"}','["Complete export confirmation at an Armenian border customs point"]','[]','["Follow the official invoice return procedure after customs confirmation"]','The government decision and 2023 amendments are verified. Exact counter locations and hours depend on the departure point and are not published in this record.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-am-research','tf-am-research-v1','https://www.arlis.am/en/acts/181106','www.arlis.am','Armenian Legal Information System','law','Eligibility, AMD 50,000 threshold, 90-day export deadline and exclusions',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-am-research','tf-am-research-v1','Standard VAT',20,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-am-research','tf-am-research-v1','Published minimum',50000,NULL,'AMD','store_day','gte','Goods from the same taxpayer in one calendar day, VAT included.');

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-am-research-v1','tf-am','tf-am-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-ge','tf-ge','official_available','https://www.rs.ge/TaxFreeInfo','Georgia Revenue Service','tax_authority','Program operation, GEL 200 threshold, packaging, exclusions and three-month deadline',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='verified_available',regional_note='The Revenue Service rules are verified. Exact refund desks and working hours are not published in this record.',updated_at=1790467200000 WHERE id='tf-ge';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-ge-research-v1','tf-ge',1,'published','available','Tax Free Georgia','Foreign citizens can reclaim Georgian VAT on qualifying goods bought from an authorized Tax Free retailer and exported from Georgia.','["Foreign citizen named on the Tax Free receipt"]','["More than GEL 200 excluding VAT on one Tax Free receipt","Perishable goods, vehicles, most export-restricted goods and specified precious goods are excluded"]','["Buy from an authorized Tax Free retailer","Obtain the special Tax Free receipt","Keep the seller''s required packaging and seal intact"]','["Passport or travel identity document","Special Tax Free receipt","Purchased goods"]','["Do not open sealed packaging before Revenue Service validation","All goods listed on the receipt must be exported"]','{"export":"Export within three months of purchase"}','["Present the goods and Tax Free receipt at the Georgian border checkpoint"]','[]','["Refund is paid only to the person named on the receipt after export is confirmed"]','The Revenue Service rules are verified. Exact refund desks and working hours are not published in this record.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-ge-research','tf-ge-research-v1','https://www.rs.ge/TaxFreeInfo','www.rs.ge','Georgia Revenue Service','tax_authority','Program operation, GEL 200 threshold, packaging, exclusions and three-month deadline',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-ge-research','tf-ge-research-v1','Standard VAT',18,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-ge-research','tf-ge-research-v1','Published minimum',200,NULL,'GEL','receipt','gt','More than GEL 200 excluding VAT on one receipt.');

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-ge-research-v1','tf-ge','tf-ge-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-mx','tf-mx','official_available','https://wwwmat.sat.gob.mx/tramites/26375/solicita-el-reintegro-de-cantidades-de-iva-a-turistas-extranjeros','Mexico Tax Administration Service (SAT)','tax_authority','Program basis, tourist eligibility, MXN 1,200 threshold and payment requirements',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='verified_available',regional_note='SAT confirms the legal program and traveler requirements. Tripto has not verified a current complete list of operating airport and seaport counters, so confirm the departure point before purchase.',updated_at=1790467200000 WHERE id='tf-mx';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-mx-research-v1','tf-mx',1,'published','available','VAT refunds for foreign tourists','Foreign tourists departing Mexico by air or sea can request a VAT refund for qualifying merchandise under the SAT program.','["Foreign visitor with tourist status","Departing Mexico by air or sea"]','["At least MXN 1,200 per establishment","Electronic payment qualifies; cash purchases are limited under the current SAT rules"]','["Obtain a compliant tax invoice showing the merchandise and VAT"]','["Original valid passport","Boarding pass or proof of departure","Tax invoices","Purchased merchandise","Refund application from the authorized concessionaire"]','["Merchandise must actually leave Mexico and be presented when requested"]','{"departure":"Complete the procedure at the authorized point before leaving Mexico"}','["Present the goods and documents to the authorized concessionaire at a covered airport or seaport"]','[]','["Refund normally returns to an electronic payment method","An authorized concessionaire may deduct its disclosed administration cost"]','SAT confirms the legal program and traveler requirements. Tripto has not verified a current complete list of operating airport and seaport counters, so confirm the departure point before purchase.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-mx-research','tf-mx-research-v1','https://wwwmat.sat.gob.mx/tramites/26375/solicita-el-reintegro-de-cantidades-de-iva-a-turistas-extranjeros','wwwmat.sat.gob.mx','Mexico Tax Administration Service (SAT)','tax_authority','Program basis, tourist eligibility, MXN 1,200 threshold and payment requirements',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-mx-research','tf-mx-research-v1','Standard VAT',16,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_thresholds (id,rule_version_id,label,amount,maximum_amount,currency,basis,comparison,notes) VALUES ('tf-th-mx-research','tf-mx-research-v1','Published minimum',1200,NULL,'MXN','other','gte','Minimum merchandise purchase per establishment.');

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-mx-research-v1','tf-mx','tf-mx-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-om','tf-om','official_partial','https://tms.taxoman.gov.om/portal/vat-faqs','Oman Tax Authority','tax_authority','Legal availability for visitors and tourists; operational details remain incomplete',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='partial',regional_note='The legal entitlement is confirmed by the Oman Tax Authority, but Tripto has not confirmed a current public list of operating traveler counters, hours, payout methods or all thresholds.',updated_at=1790467200000 WHERE id='tf-om';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-om-research-v1','tf-om',1,'published','partial','Tourist VAT refund under Oman VAT rules','Oman''s Tax Authority states that visitors and tourists can obtain a VAT refund subject to the conditions in the regulations for travel outside the GCC.','["Visitor or tourist travelling to or from Oman from outside the GCC","Eligibility depends on the detailed VAT regulations"]','["Only goods and minimum values allowed by the regulations qualify"]','["Ask the retailer whether the current tourist refund procedure is operational before purchase"]','["Passport or travel document","Tax invoice","Goods when inspection is required"]','["Keep goods available for export verification"]','{"review":"Operational deadlines require confirmation with the Tax Authority"}','["Departure locations and exact processing steps are not yet confirmed in this record"]','[]','["Refund method and operator require current confirmation"]','The legal entitlement is confirmed by the Oman Tax Authority, but Tripto has not confirmed a current public list of operating traveler counters, hours, payout methods or all thresholds.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-om-research','tf-om-research-v1','https://tms.taxoman.gov.om/portal/vat-faqs','tms.taxoman.gov.om','Oman Tax Authority','tax_authority','Legal availability for visitors and tourists; operational details remain incomplete',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_rates (id,rule_version_id,category,rate,price_includes_tax,notes) VALUES ('tf-rate-om-research','tf-om-research-v1','Standard VAT',5,1,'Use the category and rate shown on the actual invoice; reduced and exempt categories can differ.');

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-om-research-v1','tf-om','tf-om-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-uz','tf-uz','official_partial','https://taxfree.soliq.uz/static/qqs_ru-11052d43061755257353ad7f20099c0d.pdf','Uzbekistan Tax Committee','tax_authority','Official Tax Free procedure; operational details remain partial',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='partial',regional_note='An official Tax Free procedure is published, but thresholds, supported airports, hours and current operator terms remain under review.',updated_at=1790467200000 WHERE id='tf-uz';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-uz-research-v1','tf-uz',1,'published','partial','Tax Free Uzbekistan','Uzbekistan''s Tax Committee publishes a Tax Free refund procedure for foreign visitors, but Tripto has not completed a current airport-by-airport operational review.','["Foreign visitor meeting the official Tax Free procedure"]','["Qualifying goods bought from participating retailers"]','["Request the official Tax Free purchase documentation"]','["Passport","Tax Free purchase documents","Goods"]','["Keep goods available for export confirmation"]','{"review":"Confirm current filing and export deadlines in the official guide"}','["Follow the official departure validation procedure"]','[]','["Use the payment method allowed by the official Tax Free application"]','An official Tax Free procedure is published, but thresholds, supported airports, hours and current operator terms remain under review.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-uz-research','tf-uz-research-v1','https://taxfree.soliq.uz/static/qqs_ru-11052d43061755257353ad7f20099c0d.pdf','taxfree.soliq.uz','Uzbekistan Tax Committee','tax_authority','Official Tax Free procedure; operational details remain partial',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-uz-research-v1','tf-uz','tf-uz-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-hk','tf-hk','official_unavailable','https://www.fstb.gov.hk/en/treasury/general/prevailing-tax-policy.htm','Hong Kong Financial Services and the Treasury Bureau','tax_authority','Official confirmation that Hong Kong has no VAT or sales tax',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='verified_unavailable',regional_note='This refers to a general VAT/GST or sales-tax refund. Product duties and import rules are separate.',updated_at=1790467200000 WHERE id='tf-hk';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-hk-research-v1','tf-hk',1,'published','unavailable','No VAT or general sales tax','Hong Kong does not levy VAT, GST or a general sales tax, so there is no general tourist VAT refund to claim.','[]','[]','[]','[]','[]','{}','[]','[]','[]','This refers to a general VAT/GST or sales-tax refund. Product duties and import rules are separate.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-hk-research','tf-hk-research-v1','https://www.fstb.gov.hk/en/treasury/general/prevailing-tax-policy.htm','www.fstb.gov.hk','Hong Kong Financial Services and the Treasury Bureau','tax_authority','Official confirmation that Hong Kong has no VAT or sales tax',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-hk-research-v1','tf-hk','tf-hk-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);

INSERT OR REPLACE INTO tax_free_research_checks (id,territory_id,result,source_url,publisher,source_kind,finding_summary,checked_at,next_review_at) VALUES ('tf-research-official-nz','tf-nz','official_unavailable','https://www.ird.govt.nz/-/media/project/ir/home/documents/forms-and-guides/ir200---ir299/ir294/ir294-2024.pdf','New Zealand Inland Revenue','tax_authority','Official visitor guidance confirming no general GST exemption or refund',1790467200000,1806278400000);

UPDATE tax_free_territories SET status='verified_unavailable',regional_note='Supplier-exported and licensed duty-free transactions can be zero-rated, but a visitor carrying ordinary retail purchases has no general GST refund.',updated_at=1790467200000 WHERE id='tf-nz';

INSERT OR IGNORE INTO tax_free_rule_versions (id,territory_id,version_number,lifecycle,availability,program_name,summary,eligibility_json,purchases_json,store_steps_json,documents_json,goods_json,deadlines_json,customs_json,electronic_validation_json,payout_json,disclaimer,effective_from,effective_to,content_verified_at,source_checked_at,published_at,published_by,supersedes_version_id,created_at,updated_at) VALUES ('tf-nz-research-v1','tf-nz',1,'published','unavailable','No general GST refund for visitors','Visitors pay New Zealand GST like residents and cannot claim a general refund for goods or services bought in New Zealand.','[]','[]','[]','[]','[]','{}','[]','[]','[]','Supplier-exported and licensed duty-free transactions can be zero-rated, but a visitor carrying ordinary retail purchases has no general GST refund.','2026-09-27',NULL,1790467200000,1790467200000,1790467200000,'world-research-review',NULL,1790467200000,1790467200000);

INSERT OR IGNORE INTO tax_free_sources (id,rule_version_id,url,host,publisher,source_type,claim_scope,effective_from,checked_at,etag,last_modified,content_hash,last_technical_check_at,next_check_at,active) VALUES ('tf-src-nz-research','tf-nz-research-v1','https://www.ird.govt.nz/-/media/project/ir/home/documents/forms-and-guides/ir200---ir299/ir294/ir294-2024.pdf','www.ird.govt.nz','New Zealand Inland Revenue','tax_authority','Official visitor guidance confirming no general GST exemption or refund',NULL,1790467200000,NULL,NULL,NULL,1790467200000,1806278400000,1);

INSERT OR IGNORE INTO tax_free_publication_history (id,territory_id,rule_version_id,action,actor,notes,created_at) VALUES ('tf-history-nz-research-v1','tf-nz','tf-nz-research-v1','publish','world-research-review','Published after country-source review on 2026-09-27.',1790467200000);
