import {
  availableGroups,
  clockPreference,
  compareCountries,
  comparePowerCompatibility,
  countryName,
  dataset,
  flagEmoji,
  getCountry,
  groupSources,
  groupStatus,
  isMultiZone,
  listCountryCodes,
  preparationNotes,
  primaryCurrency,
  resolveTripCountries,
  sharedCallingCodeCountries,
  singleTimeZone,
  timeDifferenceMinutes,
  zoneOffsetMinutes,
} from './index.ts';

// Offline-bundled client surface, mirrors the TriptoAirlineDirectory global.
Object.assign(globalThis, {
  TriptoCountryGuide: Object.freeze({
    getCountry,
    listCountryCodes,
    countryName,
    flagEmoji,
    primaryCurrency,
    isMultiZone,
    clockPreference,
    sharedCallingCodeCountries,
    singleTimeZone,
    groupStatus,
    groupSources,
    availableGroups,
    zoneOffsetMinutes,
    timeDifferenceMinutes,
    comparePowerCompatibility,
    compareCountries,
    preparationNotes,
    resolveTripCountries,
    datasetVersion: dataset.datasetVersion,
    generatedAt: dataset.generatedAt,
    lastReviewedAt: dataset.lastReviewedAt,
    sources: dataset.sources,
    size: listCountryCodes().length,
  }),
});
