import {useEffect,useState} from "react";
import type {ComponentType,ReactNode} from "react";
import {ArrowLeftIcon,BackpackIcon,CalendarIcon,CheckCircledIcon,ChevronDownIcon,ChevronRightIcon,ClockIcon,DownloadIcon,EnvelopeClosedIcon,ExclamationTriangleIcon,FileTextIcon,GearIcon,GlobeIcon,HomeIcon,InfoCircledIcon,Link2Icon,MagnifyingGlassIcon,PaperPlaneIcon,PersonIcon,PlusIcon,QuestionMarkCircledIcon,RocketIcon,SewingPinIcon,StarIcon,UploadIcon} from "@radix-ui/react-icons";
import {BottomSheet,KeyboardInput,MobileScroll,useKeyboard} from "./mobile";

type Screen="welcome"|"authenticating"|"create"|"create-new"|"add"|"upload"|"forward"|"manual"|"manual-flight"|"manual-hotel"|"manual-activity"|"timeline-one"|"timeline"|"before"|"during"|"attention"|"timeline-empty"|"loading"|"error"|"offline"|"confirmation"|"destructive"|"account"|"past"|"booking-doc"|"booking-multiple"|"trip-documents"|"unlinked-document"|"link-document"|"document-offline"|"document-device";
type Booking={time:string;title:string;detail:string;type:"flight"|"stay"|"train"|"car"|"food"|"activity"};
type Notice={title:string;description:string;body:string;primary?:string;action?:()=>void};
const fixtures:Booking[]=[
 {time:"09:20",title:"Tel Aviv → Rome",detail:"LY 383 · Terminal 3",type:"flight"},
 {time:"14:10",title:"Airport transfer",detail:"FCO → Hotel Artemide",type:"car"},
 {time:"15:00",title:"Hotel Artemide",detail:"Check-in · 4 nights",type:"stay"},
 {time:"20:00",title:"Roscioli",detail:"Dinner reservation",type:"food"},
 {time:"09:20",title:"Rome → Florence",detail:"Train 9512",type:"train"},
 {time:"15:30",title:"Vatican Museums",detail:"Timed entry",type:"activity"},
];
const valid:Screen[]=["welcome","authenticating","create","create-new","add","upload","forward","manual","manual-flight","manual-hotel","manual-activity","timeline-one","timeline","before","during","attention","timeline-empty","loading","error","offline","confirmation","destructive","account","past","booking-doc","booking-multiple","trip-documents","unlinked-document","link-document","document-offline","document-device"];
const hashScreen=()=>{const value=location.hash.slice(1) as Screen;return valid.includes(value)?value:"welcome"};

export default function Prototype(){
 const [screen,setScreen]=useState<Screen>(hashScreen),[createReturn,setCreateReturn]=useState<Screen>("welcome"),[tour,setTour]=useState(false),[plus,setPlus]=useState(false),[selector,setSelector]=useState(false),[notice,setNotice]=useState<Notice|null>(null),[step,setStep]=useState(0),[destination,setDestination]=useState(""),[name,setName]=useState("");
 const keyboard=useKeyboard();
 const go=(next:Screen)=>{keyboard.hide();location.hash=next;setScreen(next)};
 const startCreate=(from:Screen,newTrip=false)=>{setCreateReturn(from);go(newTrip?"create-new":"create")};
 useEffect(()=>{const sync=()=>setScreen(hashScreen());addEventListener("hashchange",sync);return()=>removeEventListener("hashchange",sync)},[]);
 useEffect(()=>{if(screen==="confirmation")setNotice({title:"Add this booking?",description:"Flight to Rome",body:"LY 383 will be added to the Rome Timeline.",primary:"Add booking",action:()=>go("timeline-one")});else if(screen==="destructive")setNotice({title:"Remove this document?",description:"The flight booking will remain",body:"Only the local document copy and its booking link will be removed.",primary:"Keep document",action:()=>go("document-device")})},[screen]);
 useEffect(()=>{if(!tour&&!plus&&!selector&&!notice)return;const reset=()=>{document.querySelector<HTMLElement>(".device-screen")?.scrollTo({top:0});document.querySelector<HTMLElement>(".mobile-scroll")?.scrollTo({top:0})};reset();const interval=window.setInterval(reset,50),stop=window.setTimeout(()=>clearInterval(interval),800);return()=>{clearInterval(interval);clearTimeout(stop)}},[tour,plus,selector,notice]);
 const explain=(title:string,description:string,body:string,primary?:string,action?:()=>void)=>setNotice({title,description,body,primary,action});
 let content:ReactNode;
 const openTour=()=>{keyboard.hide();setTour(true)},openPlus=()=>{keyboard.hide();setPlus(true)},openSelector=()=>{keyboard.hide();setSelector(true)};
 if(screen==="welcome")content=<Welcome signIn={()=>go("authenticating")} tour={openTour} explain={explain}/>;
 else if(screen==="authenticating")content=<SystemState kind="auth" retry={()=>go("create")}/>;
 else if(screen==="create"||screen==="create-new")content=<Create newTrip={screen==="create-new"} destination={destination} name={name} setDestination={setDestination} setName={setName} back={()=>go(createReturn)} done={()=>go("add")}/>;
 else if(screen==="add")content=<Add back={()=>go("timeline-one")} upload={()=>go("upload")} forward={()=>go("forward")} manual={()=>go("manual")}/>;
 else if(screen==="upload")content=<UploadBooking back={()=>go("add")} done={()=>go("timeline-one")}/>;
 else if(screen==="forward")content=<ForwardBooking back={()=>go("add")} done={()=>go("timeline-one")}/>;
 else if(screen==="manual")content=<Manual back={()=>go("add")} select={s=>go(s)} done={()=>go("timeline-one")}/>;
 else if(screen==="manual-flight")content=<ManualFlight back={()=>go("manual")} done={()=>go("timeline-one")}/>;
 else if(screen==="manual-hotel")content=<ManualDetails kind="Hotel / Stay" back={()=>go("manual")} done={()=>go("timeline-one")}/>;
 else if(screen==="manual-activity")content=<ManualDetails kind="Activity / Event" back={()=>go("manual")} done={()=>go("timeline-one")}/>;
 else if(screen==="loading")content=<SystemState kind="loading" retry={()=>go("timeline")}/>;
 else if(screen==="error")content=<SystemState kind="error" retry={()=>go("timeline")}/>;
 else if(screen==="offline")content=<SystemState kind="offline" retry={()=>go("timeline")}/>;
 else if(screen==="timeline-empty")content=<EmptyTimeline plus={openPlus} account={()=>go("account")}/>;
 else if(screen==="account")content=<Account trip={()=>go("timeline")} past={()=>go("past")} tour={openTour} plus={openPlus} signOut={()=>go("welcome")} explain={explain}/>;
 else if(screen==="past")content=<Past back={()=>go("account")} trip={()=>go("timeline")}/>;
 else if(screen==="booking-doc")content=<BookingDocuments multiple={false} back={()=>go("timeline")} open={go} explain={explain}/>;
 else if(screen==="booking-multiple")content=<BookingDocuments multiple back={()=>go("trip-documents")} open={go} explain={explain}/>;
 else if(screen==="trip-documents")content=<TripDocuments back={()=>go("timeline")} open={go}/>;
 else if(screen==="unlinked-document")content=<UnlinkedDocument back={()=>go("trip-documents")} link={()=>go("link-document")}/>;
 else if(screen==="link-document")content=<LinkDocument back={()=>go("unlinked-document")} done={()=>go("trip-documents")}/>;
 else if(screen==="document-offline")content=<DocumentState offline back={()=>go("booking-doc")} explain={explain}/>;
 else if(screen==="document-device")content=<DocumentState offline={false} back={()=>go("booking-doc")} explain={explain}/>;
 else content=<Timeline mode={screen} account={()=>go("account")} plus={openPlus} selector={openSelector} documents={()=>go("trip-documents")} booking={()=>go("booking-doc")} explain={explain}/>;
 return <div className="prototype-shell"><MobileScroll className={`app-screen app-screen--${screen}`}>{content}</MobileScroll><Tour open={tour} step={step} setStep={setStep} change={setTour} start={()=>{setTour(false);startCreate("welcome")}}/><Plus open={plus} change={setPlus} add={()=>{setPlus(false);go("add")}} create={()=>{setPlus(false);startCreate(screen,true)}}/><Trips open={selector} change={setSelector} select={s=>{setSelector(false);s==="create-new"?startCreate(screen,true):go(s)}}/><NoticeSheet notice={notice} close={()=>setNotice(null)}/></div>;
}

const Brand=()=> <div className="brand" aria-label="tripto.to">tripto<span>.</span>to</div>;
function Welcome({signIn,tour,explain}:{signIn:()=>void;tour:()=>void;explain:(a:string,b:string,c:string)=>void}){const points:[[ComponentType,string],...Array<[ComponentType,string]>]=[[PaperPlaneIcon,"Depart"],[GlobeIcon,"At the airport"],[RocketIcon,"On the way"],[BackpackIcon,"At your destination"],[StarIcon,"Enjoy your trip"]];return <main className="welcome-screen" data-testid="welcome-screen"><Brand/><section className="welcome-copy"><h1>All your trip.<br/>One Timeline.</h1><p>Add bookings, we’ll tell you<br/>what matters next.</p></section><div className="journey-preview" aria-label="A simple journey from departure to destination">{points.map(([Icon,label],i)=><div className="journey-point" key={label}><span className={i===2?"active":""}><Icon/></span><strong>{label}</strong></div>)}</div><div className="welcome-actions"><button className="google-button" onClick={signIn}><span className="google-mark">G</span>Continue with Google</button><button className="text-button" onClick={tour}>Take a tour<ChevronRightIcon/></button></div><footer className="welcome-footer"><button onClick={()=>explain("Privacy Policy","Your data stays yours.","This prototype stores nothing and does not connect to production data.")}>Privacy Policy</button><span/><button onClick={()=>explain("Terms of Service","Prototype terms","This interactive concept is for product review only.")}>Terms of Service</button></footer></main>}
function Create({newTrip,destination,name,setDestination,setName,back,done}:{newTrip:boolean;destination:string;name:string;setDestination:(v:string)=>void;setName:(v:string)=>void;back:()=>void;done:()=>void}){const [datesOpen,setDatesOpen]=useState(false),[start,setStart]=useState<number|null>(12),[end,setEnd]=useState<number|null>(18);const choose=(day:number)=>{if(start===null||end!==null||day<start){setStart(day);setEnd(null)}else setEnd(day)};const range=start&&end?`Sep ${start} – Sep ${end}`:start?`Sep ${start} – Select end`:"Select dates";return <Page title={newTrip?"Create New Trip":"Create Trip"} back={back} cls="form-screen"><section className="form-heading"><span className="eyebrow">NEW TRIP</span><h1>Where are you going?</h1><p>Keep it simple. You can add the details later.</p></section><Field label="Destination"><KeyboardInput value={destination} onChange={e=>setDestination(e.target.value)} placeholder="e.g. Rome"/></Field><button className="range-field" onClick={()=>setDatesOpen(true)} aria-haspopup="dialog"><span><small>Travel dates</small><strong>{range}</strong></span><CalendarIcon/></button><Field label="Trip name · Optional"><KeyboardInput value={name} onChange={e=>setName(e.target.value)} placeholder={destination?`${destination} trip`:"e.g. Summer in Rome"}/></Field><div className="task-footer"><button className="primary-button" disabled={!destination.trim()||!start||!end} onClick={done}>Create trip<ChevronRightIcon/></button></div><BottomSheet open={datesOpen} onOpenChange={setDatesOpen} title="Travel dates" description="Select a start date, then an end date"><div className="date-sheet"><div className="date-month"><strong>September 2026</strong></div><div className="date-week" aria-hidden="true">{["S","M","T","W","T","F","S"].map((d,i)=><span key={`${d}-${i}`}>{d}</span>)}</div><div className="date-grid">{[null,null,...Array.from({length:30},(_,i)=>i+1)].map((day,i)=>day?<button key={day} className={`${day===start||day===end?"edge ":""}${start&&end&&day>start&&day<end?"inside":""}`} onClick={()=>choose(day)} aria-label={`September ${day}, 2026`} aria-pressed={day===start||day===end}>{day}</button>:<span key={`empty-${i}`}/>)}</div><button className="primary-button" disabled={!start||!end} onClick={()=>setDatesOpen(false)}>Use these dates<ChevronRightIcon/></button></div></BottomSheet></Page>}
function Add({back,upload,forward,manual}:{back:()=>void;upload:()=>void;forward:()=>void;manual:()=>void}){return <Page title="Add to Rome" back={back}><section className="task-intro"><span className="eyebrow">ADD BOOKING</span><h1>How would you like<br/>to add it?</h1><p>Everything you add will appear in the Timeline.</p></section><div className="choice-list"><Choice Icon={UploadIcon} title="Upload Booking" detail="Ticket, confirmation, or reservation" click={upload}/><Choice Icon={EnvelopeClosedIcon} title="Forward Confirmation Email" detail="Send it to bookings@tripto.to" click={forward}/><Choice Icon={PlusIcon} title="Add Manually" detail="For anything without a document" click={manual}/></div><div className="trust-note"><CheckCircledIcon/>We never guess uncertain travel details.</div></Page>}
function UploadBooking({back,done}:{back:()=>void;done:()=>void}){const [selected,setSelected]=useState(false);return <Page title="Upload Booking" back={back} cls="focused-flow"><section className="task-intro"><span className="eyebrow">ROME</span><h1>Add a confirmation.</h1><p>Choose a ticket, booking confirmation, or reservation.</p></section><button className={`upload-zone ${selected?"selected":""}`} onClick={()=>setSelected(true)}><span>{selected?<CheckCircledIcon/>:<UploadIcon/>}</span><strong>{selected?"LY383-ticket.pdf":"Choose a file"}</strong><small>{selected?"Ready to review · stored on this device":"PDF, image, or supported booking file"}</small></button>{selected&&<section className="review-card"><span className="eyebrow">REVIEW</span><strong>Flight to Rome</strong><small>LY 383 · Tel Aviv → Rome</small><em>No uncertain details</em></section>}<p className="prototype-note">Prototype only — no file leaves this device.</p><div className="task-footer"><button className="primary-button" disabled={!selected} onClick={done}>Add to Timeline<ChevronRightIcon/></button></div></Page>}
function ForwardBooking({back,done}:{back:()=>void;done:()=>void}){const [copied,setCopied]=useState(false);return <Page title="Forward Confirmation" back={back} cls="focused-flow"><section className="task-intro"><span className="eyebrow">BOOKING EMAIL</span><h1>Forward it to tripto.to.</h1><p>Use your verified email. We’ll keep uncertain bookings for review.</p></section><div className="forward-address"><EnvelopeClosedIcon/><span><small>Send confirmations to</small><strong>bookings@tripto.to</strong></span></div><button className="secondary-button" onClick={()=>setCopied(true)}>{copied?<CheckCircledIcon/>:<FileTextIcon/>}{copied?"Address copied":"Copy email address"}</button><div className="forward-steps"><div><span>1</span><p>Forward the original confirmation.</p></div><div><span>2</span><p>We match it to the right trip only when reliable.</p></div><div><span>3</span><p>Ambiguous bookings ask you to choose.</p></div></div><div className="task-footer"><button className="primary-button" onClick={done}>I’ve forwarded it<ChevronRightIcon/></button></div></Page>}
function Manual({back,select,done}:{back:()=>void;select:(s:Screen)=>void;done:()=>void}){const cats:[string,ComponentType][]=[["Flight",PaperPlaneIcon],["Hotel / Stay",HomeIcon],["Train",RocketIcon],["Car Rental",BackpackIcon],["Transfer",SewingPinIcon],["Cruise",GlobeIcon],["Ferry",PaperPlaneIcon],["Restaurant",StarIcon],["Activity / Event",CalendarIcon],["Other",PlusIcon]];return <Page title="Add Manually" back={back}><section className="compact-intro"><h1>What are you adding?</h1><p>Choose a type to see only the fields you need.</p></section><label className="search-field"><MagnifyingGlassIcon/><input aria-label="Search booking types" placeholder="Search booking types"/></label><div className="category-grid">{cats.map(([label,Icon])=><button key={label} onClick={()=>label==="Flight"?select("manual-flight"):label==="Hotel / Stay"?select("manual-hotel"):label==="Activity / Event"?select("manual-activity"):done()}><span><Icon/></span><strong>{label}</strong></button>)}</div></Page>}
function ManualFlight({back,done}:{back:()=>void;done:()=>void}){const [airline,setAirline]=useState(""),[number,setNumber]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[departure,setDeparture]=useState(false);return <Page title="Add Flight" back={back} cls="manual-form"><section className="compact-intro"><span className="eyebrow">FLIGHT</span><h1>Flight details</h1><p>Enter only what you know. Unknown fields stay empty.</p></section><div className="field-pair"><Field label="Airline"><KeyboardInput value={airline} onChange={e=>setAirline(e.target.value)} placeholder="e.g. EL AL"/></Field><Field label="Flight number"><KeyboardInput value={number} onChange={e=>setNumber(e.target.value)} placeholder="e.g. LY 383"/></Field></div><div className="field-pair"><Field label="From"><KeyboardInput value={from} onChange={e=>setFrom(e.target.value)} placeholder="TLV"/></Field><Field label="To"><KeyboardInput value={to} onChange={e=>setTo(e.target.value)} placeholder="FCO"/></Field></div><button className="range-field" onClick={()=>setDeparture(true)}><span><small>Departure</small><strong>{departure?"Aug 28 · 09:20":"Select date & time"}</strong></span><CalendarIcon/></button><div className="task-footer"><button className="primary-button" disabled={!number.trim()||!from.trim()||!to.trim()||!departure} onClick={done}>Add Flight<ChevronRightIcon/></button></div></Page>}
function ManualDetails({kind,back,done}:{kind:"Hotel / Stay"|"Activity / Event";back:()=>void;done:()=>void}){const hotel=kind==="Hotel / Stay";const [title,setTitle]=useState(""),[location,setLocation]=useState(""),[date,setDate]=useState(false);return <Page title={hotel?"Add Hotel":"Add Activity"} back={back} cls="manual-form"><section className="compact-intro"><span className="eyebrow">{kind.toUpperCase()}</span><h1>{hotel?"Stay details":"Activity details"}</h1><p>Enter only confirmed information. You can add more later.</p></section><Field label={hotel?"Property name":"Activity name"}><KeyboardInput value={title} onChange={e=>setTitle(e.target.value)} placeholder={hotel?"e.g. Hotel Artemide":"e.g. Vatican Museums"}/></Field><Field label="Location · Optional"><KeyboardInput value={location} onChange={e=>setLocation(e.target.value)} placeholder="Address or city"/></Field><button className="range-field" onClick={()=>setDate(true)}><span><small>{hotel?"Check-in and check-out":"Date and time"}</small><strong>{date?(hotel?"Aug 28 – Sep 1":"Aug 29 · 15:30"):(hotel?"Select dates":"Select date & time")}</strong></span><CalendarIcon/></button><div className="task-footer"><button className="primary-button" disabled={!title.trim()||!date} onClick={done}>{hotel?"Add Stay":"Add Activity"}<ChevronRightIcon/></button></div></Page>}
function Timeline({mode,account,plus,selector,documents,booking,explain}:{mode:Screen;account:()=>void;plus:()=>void;selector:()=>void;documents:()=>void;booking:()=>void;explain:(a:string,b:string,c:string,d?:string,e?:()=>void)=>void}){const data=mode==="timeline-one"?fixtures.slice(0,1):fixtures;const detail=(item:Booking)=>item.type==="flight"?booking():explain(item.title,item.time,item.detail,"Done");return <main className="light-screen timeline-screen"><header className="trip-header"><button className="trip-title" onClick={selector}><span>Rome</span><ChevronDownIcon/><small>Aug 28 – Sep 4</small></button><div className="trip-actions"><button className="icon-button" onClick={documents} aria-label="Tickets and documents"><FileTextIcon/></button><button className="icon-button" onClick={account} aria-label="Account"><PersonIcon/></button></div></header><section className="timeline-content">{mode==="timeline-one"&&<div className="timeline-confirmation" role="status"><CheckCircledIcon/><span><strong>Flight added</strong><small>Your Timeline is ready.</small></span></div>} {mode==="before"&&<Context tone="warm" label="6 DAYS TO GO" title="Before you go" copy="Boarding pass not saved" action="Review" click={()=>explain("Before you go","1 item needs attention","Save the boarding pass before leaving for the airport.","Mark reviewed")}/>} {mode==="during"&&<Context tone="navy" label="NEXT · 24 MIN" title="Train to Florence" copy="09:20 · Platform 8" action="Open ticket" click={booking}/>} {mode==="attention"&&<Context tone="warm" label="NEEDS ATTENTION" title="1 document needs linking" copy="Keep every ticket with the right booking." action="Review document" click={()=>goToHash("unlinked-document")}/>} {mode==="timeline"&&<div className="timeline-kicker"><span>6 days to go</span><strong>Everything in one place.</strong></div>}<Day label="THU · AUG 28"/><div className="timeline-list">{data.slice(0,4).map((b,i)=><BookingRow key={b.title} item={b} first={i===0} hasTicket={b.type==="flight"||b.type==="stay"} click={()=>detail(b)}/>)}</div>{data.length>4&&<><Day label="FRI · AUG 29"/><div className="timeline-list">{data.slice(4).map(b=><BookingRow key={b.title} item={b} hasTicket={b.type==="train"||b.type==="activity"} click={()=>detail(b)}/>)}</div></>}</section><Nav active="trip" trip={()=>document.querySelector<HTMLElement>(".mobile-scroll")?.scrollTo({top:0,behavior:"smooth"})} plus={plus} account={account}/></main>}
const goToHash=(screen:Screen)=>{location.hash=screen};
function BookingRow({item,first,hasTicket,click}:{item:Booking;first?:boolean;hasTicket?:boolean;click:()=>void}){const Icon=item.type==="flight"?PaperPlaneIcon:item.type==="stay"?HomeIcon:item.type==="train"?RocketIcon:item.type==="car"?SewingPinIcon:item.type==="food"?StarIcon:CalendarIcon;return <button className={`timeline-row ${first?"next":""}`} onClick={click}><time>{item.time}</time><span className="timeline-icon"><Icon/></span><span className="timeline-copy"><strong>{item.title}</strong><small>{item.detail}</small>{hasTicket&&<em>Ticket available</em>}</span><ChevronRightIcon/></button>}

type DocumentRowProps={title:string;detail:string;status:"offline"|"device"|"attention";click:()=>void};
function DocumentRow({title,detail,status,click}:DocumentRowProps){return <button className={`document-row ${status}`} onClick={click}><span className="document-icon"><FileTextIcon/></span><span className="document-copy"><strong>{title}</strong><small>{detail}</small><em>{status==="offline"?"Available offline":status==="device"?"Stored on this device":"Not linked to a booking"}</em></span>{status==="offline"?<CheckCircledIcon/>:status==="attention"?<ExclamationTriangleIcon/>:<ChevronRightIcon/>}</button>}
function BookingDocuments({multiple,back,open,explain}:{multiple:boolean;back:()=>void;open:(s:Screen)=>void;explain:(a:string,b:string,c:string,d?:string,e?:()=>void)=>void}){return <Page title={multiple?"Hotel":"Flight"} back={back} cls="document-page"><section className="booking-summary"><span className="eyebrow">{multiple?"HOTEL · CONFIRMED":"FLIGHT · CONFIRMED"}</span><h1>{multiple?"Hotel Artemide":"Tel Aviv → Rome"}</h1><p>{multiple?"Aug 28 – Sep 1 · 4 nights":"LY 383 · 09:20"}</p></section><section className="documents-section"><div className="section-heading"><span><strong>Tickets & Documents</strong><small>{multiple?"2 files":"2 files · 1 traveler"}</small></span></div><div className="document-list">{multiple?<><DocumentRow title="Reservation Confirmation" detail="Hotel Artemide" status="offline" click={()=>open("document-offline")}/><DocumentRow title="Hotel Voucher" detail="Check-in details" status="device" click={()=>open("document-device")}/></>:<><DocumentRow title="Boarding Pass — Arthur" detail="LY 383 · TLV → FCO" status="offline" click={()=>open("document-offline")}/><DocumentRow title="E-ticket" detail="LY383-ticket.pdf" status="device" click={()=>open("document-device")}/></>}</div></section><button className="secondary-button" onClick={()=>explain("Booking details",multiple?"Hotel Artemide":"LY 383",multiple?"Check-in 15:00 · Confirmation HA-7865421":"Terminal 3 · Gate not assigned · Seat 12A","Done")}>View booking details<ChevronRightIcon/></button></Page>}
function TripDocuments({back,open}:{back:()=>void;open:(s:Screen)=>void}){return <Page title="Tickets & Documents" back={back} cls="document-page trip-documents-page"><section className="document-overview"><span className="eyebrow">ROME · AUG 28 – SEP 4</span><h1>Everything for your trip.</h1><p>Tickets stay with the booking they belong to.</p></section><DocumentGroup label="FLIGHT TO ROME"><DocumentRow title="Boarding Pass — Arthur" detail="LY 383 · TLV → FCO" status="offline" click={()=>open("booking-doc")}/><DocumentRow title="E-ticket" detail="LY383-ticket.pdf" status="device" click={()=>open("booking-multiple")}/></DocumentGroup><DocumentGroup label="HOTEL ARTEMIDE"><DocumentRow title="Reservation Confirmation" detail="Aug 28 – Sep 1" status="offline" click={()=>open("booking-multiple")}/></DocumentGroup><DocumentGroup label="ROME → FLORENCE"><DocumentRow title="Train Ticket" detail="Train 9512" status="offline" click={()=>open("document-offline")}/></DocumentGroup><section className="attention-document"><span><ExclamationTriangleIcon/></span><div><strong>1 document needs attention</strong><small>reservation.pdf is not linked</small></div><button onClick={()=>open("unlinked-document")}>Review<ChevronRightIcon/></button></section></Page>}
function DocumentGroup({label,children}:{label:string;children:ReactNode}){return <section className="document-group"><span className="group-label">{label}</span><div className="document-list">{children}</div></section>}
function UnlinkedDocument({back,link}:{back:()=>void;link:()=>void}){return <Page title="Needs Attention" back={back} cls="document-page"><section className="document-state-hero attention"><span><ExclamationTriangleIcon/></span><span className="eyebrow">NOT LINKED</span><h1>reservation.pdf</h1><p>We kept this file, but could not reliably match it to a booking.</p></section><div className="storage-note"><FileTextIcon/><span><strong>Stored on this device</strong><small>The original file has not been synced to your account.</small></span></div><div className="task-footer document-actions"><button className="primary-button" onClick={link}><Link2Icon/>Link to Booking</button><button className="text-button" onClick={back}>Keep unlinked</button></div></Page>}
function LinkDocument({back,done}:{back:()=>void;done:()=>void}){const [selected,setSelected]=useState<string|null>(null);const options=["Flight to Rome","Hotel Artemide","Rome → Florence","Vatican Museums","Other / Keep unlinked"];return <Page title="Link to Booking" back={back} cls="document-page"><section className="compact-intro"><h1>Where does this belong?</h1><p>Choose the booking that matches reservation.pdf.</p></section><div className="link-options">{options.map(label=><button className={selected===label?"selected":""} key={label} onClick={()=>setSelected(label)}><span>{label}</span>{selected===label?<CheckCircledIcon/>:<ChevronRightIcon/>}</button>)}</div><div className="task-footer"><button className="primary-button" disabled={!selected} onClick={done}>Save link<ChevronRightIcon/></button></div></Page>}
function DocumentState({offline,back,explain}:{offline:boolean;back:()=>void;explain:(a:string,b:string,c:string,d?:string,e?:()=>void)=>void}){return <Page title="Document" back={back} cls="document-page"><section className="document-state-hero"><span><FileTextIcon/></span><span className="eyebrow">BOARDING PASS</span><h1>LY 383</h1><p>Tel Aviv → Rome · Arthur</p></section><div className={`availability-card ${offline?"ready":"local"}`}><span>{offline?<CheckCircledIcon/>:<DownloadIcon/>}</span><div><strong>{offline?"Available offline":"Available on this device"}</strong><small>{offline?"Verified copy opens without internet.":"Original file is stored locally and is not backed up."}</small></div></div><div className="document-meta"><div><small>File</small><strong>LY383-boarding-pass.pdf</strong></div><div><small>Booking</small><strong>Flight to Rome</strong></div></div><div className="task-footer document-actions"><button className="primary-button" onClick={()=>explain("Boarding Pass","LY 383 · Arthur","The verified prototype document opened successfully.","Done")}>Open Boarding Pass<ChevronRightIcon/></button><button className="text-button danger" onClick={()=>explain("Remove this document?","The flight booking will remain","Only this document association and local copy would be removed. The booking is never deleted with it.","Keep document")}>Remove document</button></div></Page>}
function SystemState({kind,retry}:{kind:"auth"|"loading"|"error"|"offline";retry:()=>void}){const auth=kind==="auth",loading=kind==="loading",error=kind==="error";const title=auth?"Signing you in…":loading?"Loading your Timeline…":error?"We couldn’t load your trip":"You’re offline";const copy=auth?"Securely checking your Google account.":loading?"Your bookings and documents are on the way.":error?"Check your connection and try again. Your saved data is safe.":"Saved trip details remain available on this device.";return <main className={`system-state ${kind}`} aria-busy={auth||loading}><Brand/><section><span className="system-state-icon">{error?<ExclamationTriangleIcon/>:kind==="offline"?<DownloadIcon/>:<span className="loading-ring"/>}</span><h1>{title}</h1><p>{copy}</p>{(!auth&&!loading)&&<button className="primary-button" onClick={retry}>{error?"Try again":"Open saved trip"}<ChevronRightIcon/></button>}{auth&&<button className="text-button" onClick={retry}>Continue in prototype</button>}</section></main>}
function EmptyTimeline({plus,account}:{plus:()=>void;account:()=>void}){return <main className="light-screen timeline-screen empty-timeline"><header className="trip-header"><button className="trip-title"><span>Rome</span><ChevronDownIcon/><small>Dates not set</small></button><div className="trip-actions"><button className="icon-button" onClick={account} aria-label="Account"><PersonIcon/></button></div></header><section className="empty-timeline-body"><span className="eyebrow">START BUILDING</span><div className="empty-icon"><PlusIcon/></div><h1>No plans yet</h1><p>Add your first flight, stay, train, or activity.</p><button className="primary-button" onClick={plus}>Add booking<PlusIcon/></button></section><Nav active="trip" trip={()=>{}} plus={plus} account={account}/></main>}
function Account({trip,past,tour,plus,signOut,explain}:{trip:()=>void;past:()=>void;tour:()=>void;plus:()=>void;signOut:()=>void;explain:(a:string,b:string,c:string,d?:string,e?:()=>void)=>void}){return <main className="light-screen account-screen"><Header title="Account"/><section className="profile"><div>DB</div><span><strong>Dvir Ben-David</strong><small>Google account</small></span></section><Group label="TRIP HISTORY"><Row Icon={ClockIcon} title="Past trips" detail="Completed travel" click={past}/><Row Icon={PaperPlaneIcon} title="Cancelled trips" detail="Cancelled bookings and trips" click={()=>explain("Cancelled trips","No cancelled trips","Cancelled travel remains available here without competing with active trip switching.","Done")}/></Group><Group label="BOOKING EMAIL"><Row Icon={EnvelopeClosedIcon} title="bookings@tripto.to" detail="1 verified sender" click={()=>explain("Booking email","bookings@tripto.to","Forward confirmations from your verified email. Gmail access is not required.","Done")}/></Group><Group label="HELP"><Row Icon={QuestionMarkCircledIcon} title="Take the tour" detail="How tripto.to works" click={tour}/><Row Icon={InfoCircledIcon} title="Support & privacy" detail="Help, Privacy, Terms" click={()=>explain("Support & privacy","Prototype help center","Privacy, terms, and support links will open here in the production app.","Done")}/></Group><Group label="ACCOUNT"><Row Icon={GearIcon} title="Sign out" detail="Keep unsynced changes safe" click={()=>explain("Sign out?","Your prototype trip stays local","Production will warn before signing out when unsynced changes exist.","Sign out",signOut)}/></Group><Nav active="account" trip={trip} plus={plus} account={()=>document.querySelector<HTMLElement>(".mobile-scroll")?.scrollTo({top:0,behavior:"smooth"})}/></main>}
function Past({back,trip}:{back:()=>void;trip:()=>void}){return <Page title="Past Trips" back={back}><section className="compact-intro"><h1>Your travel history</h1><p>Completed trips stay easy to revisit.</p></section><div className="past-list">{[["Lisbon","May 4 – May 9, 2026"],["Berlin","Nov 12 – Nov 16, 2025"]].map(([a,b])=><button key={a} onClick={trip}><span><strong>{a}</strong><small>{b}</small></span><em>Completed</em><ChevronRightIcon/></button>)}</div></Page>}

function Tour({open,step,setStep,change,start}:{open:boolean;step:number;setStep:(v:number)=>void;change:(v:boolean)=>void;start:()=>void}){const steps:[string,string,ComponentType][]=[["Create your trip","Tell tripto.to where and when you’re travelling.",SewingPinIcon],["Add your bookings","Upload, forward a confirmation, or add it manually.",UploadIcon],["Everything becomes one Timeline","Flights, stays, trains, and plans appear in travel order.",ClockIcon],["Know what matters next","See the next important thing before and during your trip.",PaperPlaneIcon]];const [title,copy,Icon]=steps[step];return <BottomSheet open={open} onOpenChange={v=>{change(v);if(!v)setStep(0)}} title="Take a tour" description="Four simple steps"><div className="tour-body"><div className="tour-visual"><Icon/></div><span className="eyebrow">STEP {step+1} OF 4</span><h2>{title}</h2><p>{copy}</p><div className="tour-dots">{steps.map((_,i)=><span className={i===step?"active":""} key={i}/>)}</div><button className="primary-button" onClick={step<3?()=>setStep(step+1):start}>{step<3?"Continue":"Start planning"}<ChevronRightIcon/></button><button className="text-button sheet-close" onClick={()=>change(false)}>Close</button></div></BottomSheet>}
function Plus({open,change,add,create}:{open:boolean;change:(v:boolean)=>void;add:()=>void;create:()=>void}){return <BottomSheet open={open} onOpenChange={change} title="What would you like to do?" description="Rome · Aug 28 – Sep 4"><div className="choice-list sheet-choice-list"><Choice Icon={PlusIcon} title="Add Booking" detail="Add something to Rome" click={add}/><Choice Icon={PaperPlaneIcon} title="Create New Trip" detail="Start planning another trip" click={create}/></div></BottomSheet>}
function Trips({open,change,select}:{open:boolean;change:(v:boolean)=>void;select:(s:Screen)=>void}){return <BottomSheet open={open} onOpenChange={change} title="Switch trip" description="Active and upcoming"><div className="trip-options"><button className="selected" onClick={()=>select("timeline")}><span><strong>Rome</strong><small>Aug 28 – Sep 4 · Active</small></span><CheckCircledIcon/></button><button onClick={()=>select("timeline-one")}><span><strong>London</strong><small>Sep 12 – Sep 18 · Upcoming</small></span><ChevronRightIcon/></button><button onClick={()=>select("create-new")}><PlusIcon/><strong>Create New Trip</strong></button></div></BottomSheet>}
function NoticeSheet({notice,close}:{notice:Notice|null;close:()=>void}){const finish=()=>{const action=notice?.action;close();action?.()};return <BottomSheet open={Boolean(notice)} onOpenChange={open=>{if(!open)close()}} title={notice?.title||"Details"} description={notice?.description}><div className="notice-body"><p>{notice?.body}</p><button className="primary-button" onClick={finish}>{notice?.primary||"Done"}<ChevronRightIcon/></button></div></BottomSheet>}

function Page({title,back,children,cls=""}:{title:string;back:()=>void;children:ReactNode;cls?:string}){return <main className={`task-page ${cls}`}><Header title={title} back={back}/>{children}</main>}
function Header({title,back,action}:{title:string;back?:()=>void;action?:ReactNode}){return <header className="app-header">{back?<button className="icon-button" onClick={back} aria-label="Back"><ArrowLeftIcon/></button>:<span/>}<strong>{title}</strong>{action||<span/>}</header>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field-group"><span>{label}</span>{children}</label>}
function Choice({Icon,title,detail,click}:{Icon:ComponentType;title:string;detail:string;click:()=>void}){return <button className="choice-row" onClick={click}><span className="choice-icon"><Icon/></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRightIcon/></button>}
function Context({tone,label,title,copy,action,click}:{tone:string;label:string;title:string;copy:string;action:string;click?:()=>void}){return <section className={`context-card ${tone}`}><span className="eyebrow">{label}</span><h2>{title}</h2><p>{copy}</p><button onClick={click}>{action}<ChevronRightIcon/></button></section>}
function Day({label}:{label:string}){return <div className="day-heading"><strong>{label}</strong><i/></div>}
function Group({label,children}:{label:string;children:ReactNode}){return <section className="account-group"><span className="group-label">{label}</span><div>{children}</div></section>}
function Row({Icon,title,detail,click}:{Icon:ComponentType;title:string;detail:string;click?:()=>void}){return <button onClick={click}><span><Icon/></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRightIcon/></button>}
function Nav({active,trip,plus,account}:{active:"trip"|"account";trip:()=>void;plus:()=>void;account:()=>void}){return <nav className="bottom-nav" aria-label="Primary navigation"><button className={active==="trip"?"active":""} onClick={trip}><ClockIcon/><span>Trip</span></button><button className="add-nav" onClick={plus} aria-label="Add"><PlusIcon/></button><button className={active==="account"?"active":""} onClick={account}><PersonIcon/><span>Account</span></button></nav>}
