#!/usr/bin/env node
// Single generator for the crawl surface. Reads seo/site.json (the hand-edited
// route manifest) and writes:
//   seo/manifest.json   per-page content hash + lastmod (bundled into the worker,
//                       which uses it to decide which URLs IndexNow still needs)
//   public/sitemap.xml  canonical, indexable, 200-only URLs
//   public/robots.txt   production rules (non-production hosts get their own
//                       rules from the worker)
//   public/<key>.txt    the IndexNow key file
// lastmod only moves when a page's normalized content changes, so per-deploy
// cache-busting tokens (?v=..., tripto-asset-ver) never fake a modification.
// `--check` verifies the committed outputs are current without writing.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const site = JSON.parse(readFileSync(join(root, "seo/site.json"), "utf8"));
const manifestPath = join(root, "seo/manifest.json");
const previous = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, "utf8")) : { pages: [] };
const previousByPath = new Map(previous.pages.map((page) => [page.path, page]));
const today = process.env.SEO_BUILD_DATE || new Date().toISOString().slice(0, 10);

export function normalizePage(html) {
  return html
    .replace(/\?v=[^"'\s>&]+/g, "?v=")
    .replace(/(<meta\s+name="tripto-asset-ver"\s+content=")[^"]*"/g, '$1"');
}

const pages = site.pages.map(({ path, file }) => {
  const html = readFileSync(join(root, "public", file), "utf8");
  const hash = createHash("sha256").update(normalizePage(html)).digest("hex").slice(0, 16);
  const before = previousByPath.get(path);
  return { path, url: site.origin + path, hash, lastmod: before && before.hash === hash ? before.lastmod : today };
});

const manifest = JSON.stringify({ note: "Generated by scripts/seo-build.mjs from seo/site.json. Do not edit.", pages }, null, 2) + "\n";

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...pages.map((page) => `  <url><loc>${page.url}</loc><lastmod>${page.lastmod}</lastmod></url>`),
  "</urlset>",
  "",
].join("\n");

const robots = [
  "# Generated by scripts/seo-build.mjs from seo/site.json. Do not edit.",
  "# Public pages are crawlable. In-app routes hold private trip data and are",
  "# also served with X-Robots-Tag: noindex. /api/ stays crawlable on purpose:",
  "# blocking it breaks rendering of the home page, and every API response is",
  "# noindex and requires a session.",
  "User-agent: *",
  "Allow: /",
  ...[...site.appRoutes.map((segment) => `/${segment}`), ...site.robotsDisallowExtra].sort().map((path) => `Disallow: ${path}`),
  "",
  `Sitemap: ${site.origin}/sitemap.xml`,
  "",
].join("\n");

const outputs = [
  [manifestPath, manifest],
  [join(root, "public/sitemap.xml"), sitemap],
  [join(root, "public/robots.txt"), robots],
  [join(root, `public/${site.indexNowKey}.txt`), site.indexNowKey],
];

if (check) {
  // lastmod depends on the build date, so compare everything but the dates.
  const undated = (text) => text.replace(/\d{4}-\d{2}-\d{2}/g, "");
  const stale = outputs.filter(([file, body]) => !existsSync(file) || undated(readFileSync(file, "utf8")) !== undated(body));
  if (stale.length) {
    console.error(`seo-build: stale outputs (run node scripts/seo-build.mjs): ${stale.map(([file]) => file.slice(root.length + 1)).join(", ")}`);
    process.exit(1);
  }
  console.log("seo-build: sitemap, robots, manifest and IndexNow key are current.");
} else {
  for (const [file, body] of outputs) writeFileSync(file, body);
  const changed = pages.filter((page) => previousByPath.get(page.path)?.hash !== page.hash).map((page) => page.path);
  console.log(`seo-build: ${pages.length} public URLs; changed since last build: ${changed.length ? changed.join(", ") : "none"}.`);
}
